-- ================================================================
-- boot
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-11T21:37:10Z from components:
--   snippet header
--   lua     main
-- ================================================================

-- ==== component: header (snippet) ====

-- boot.lua — the first program the OS runs.
--
-- Kept intentionally tiny: it starts the shell (os.lua) in the
-- foreground, so boot.lua is paused underneath it. A launch returns
-- immediately while the child runs on top, so nothing may follow the
-- Launch() call except the next tick — that tick only happens once the
-- shell has exited, and the OS then has nothing left to run.
--
-- If you want a different startup program, either replace os.lua or
-- edit the Launch() call below.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run spibuild os/boot` from the repo
-- root. The generated boot.lua is written to the parent folder.

-- ==== component: main (lua) ====

function setup()
    local ok, err = Launch("core/os.prg")
    if not ok then
        print("boot: cannot start core/os.prg: " .. tostring(err) .. " trying .lua file")
        ok, err = Launch("core/os.lua")
        if not ok then
            print("boot: cannot start core/os.lua: " .. tostring(err))
        end
    end
end

function tick()
    ExitProgram()
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
