-- ================================================================
-- demo
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-14T23:27:59Z from components:
--   snippet header
--   lua     main
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = true


-- ==== sdk: screen (read-only; unused functions stripped) ====

-- SDK: Screen
-- Summary: Text-mode drawing on the base layer: text, boxes, fills, block moves.
-- Namespaces: Screen
--
-- A framework file the IDE injects, read-only, into programs that
-- select it. Its format is a contract with the builder:
--   * everything above the first top-level `function` is the preamble
--     and is always emitted;
--   * each `function Name.Sub(...)` ... `end` block (both at column 0)
--     is emitted only when the program refers to Name.Sub, directly or
--     from another emitted block;
--   * a top-level `local function helper(...)` ... `end` block is
--     emitted when an emitted block refers to `helper`;
--   * the `--- Name.Sub(x, y [, attr])` line above a block is its
--     signature for completion and parameter help; the `--` lines that
--     follow describe it.
--
-- Conventions: coordinates are 0-based cells; region calls take the two
-- inclusive corners (x1, y1, x2, y2), unlike the raw ScreenX calls,
-- which take (x, y, w, h). Every call returns what the OS call returns
-- (true, or nil and a message).

Screen = Screen or {}
Screen.COLS = 40
Screen.ROWS = 30
Screen.SINGLE = 1      -- box style: single line
Screen.DOUBLE = 2      -- box style: double line
Screen.INVERT = 0x80   -- attribute bit: swap foreground and background

-- Inclusive corners to (x, y, w, h), in either corner order.
local function region(x1, y1, x2, y2)
    if x2 < x1 then x1, x2 = x2, x1 end
    if y2 < y1 then y1, y2 = y2, y1 end
    return x1, y1, x2 - x1 + 1, y2 - y1 + 1
end

--- Screen.Mode(mode)
-- Selects a screen mode: 0 (40x30 B&W), 1 (40x30 colour), 10 (320x240
-- pixels). Switching clears the screen.
function Screen.Mode(mode)
    return ScreenMode(mode)
end

--- Screen.OutText(x, y, text [, attr])
-- Writes a string from (x, y), wrapping at the right edge. One display
-- op however long the text.
function Screen.OutText(x, y, text, attr)
    return ScreenWrite(x, y, tostring(text), attr)
end

--- Screen.CenterText(y, text [, attr])
-- Writes a string centred on row `y`.
function Screen.CenterText(y, text, attr)
    text = tostring(text)
    local x = (Screen.COLS - #text) // 2
    if x < 0 then x = 0 end
    return ScreenWrite(x, y, text, attr)
end

--- Screen.RightText(y, text [, attr])
-- Writes a string ending at the right edge of row `y`.
function Screen.RightText(y, text, attr)
    text = tostring(text)
    local x = Screen.COLS - #text
    if x < 0 then x = 0 end
    return ScreenWrite(x, y, text, attr)
end

--- Screen.Printf(x, y, format, ...)
-- string.format, written at (x, y).
function Screen.Printf(x, y, format, ...)
    return ScreenWrite(x, y, string.format(format, ...))
end

--- Screen.Clean(x1, y1, x2, y2 [, char [, attr]])
-- Blanks the cells between two corners (inclusive): `char` defaults to
-- space and `attr` to 0.
function Screen.Clean(x1, y1, x2, y2, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenFill(x, y, w, h, char or 32, attr or 0)
end

--- Screen.Fill(x1, y1, x2, y2, char [, attr])
-- Fills the cells between two corners with a character and attribute.
function Screen.Fill(x1, y1, x2, y2, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenFill(x, y, w, h, char, attr or 0)
end

--- Screen.HLine(x1, x2, y [, char [, attr]])
-- A horizontal line of `char` (default: the box-drawing horizontal).
function Screen.HLine(x1, x2, y, char, attr)
    local x, _, w = region(x1, y, x2, y)
    return ScreenFill(x, y, w, 1, char or 196, attr or 0)
end

--- Screen.VLine(x, y1, y2 [, char [, attr]])
-- A vertical line of `char` (default: the box-drawing vertical).
function Screen.VLine(x, y1, y2, char, attr)
    local _, y, _, h = region(x, y1, x, y2)
    return ScreenFill(x, y, 1, h, char or 179, attr or 0)
end

--- Screen.Box(x1, y1, x2, y2 [, style [, attr]])
-- A frame between two corners: style Screen.SINGLE (default) or
-- Screen.DOUBLE. The inside is left alone.
function Screen.Box(x1, y1, x2, y2, style, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenBox(x, y, w, h, style or 1, attr or 0)
end

--- Screen.Window(x1, y1, x2, y2 [, title [, style [, attr]]])
-- A blank window: the inside cleared, a frame around it and an optional
-- title on the top edge.
function Screen.Window(x1, y1, x2, y2, title, style, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    attr = attr or 0
    ScreenFill(x, y, w, h, 32, attr)
    local ok, err = ScreenBox(x, y, w, h, style or 1, attr)
    if ok and title and #tostring(title) > 0 then
        local label = " " .. tostring(title) .. " "
        local tx = x + (w - #label) // 2
        if tx < x + 1 then tx = x + 1 end
        ScreenWrite(tx, y, label:sub(1, w - 2), attr)
    end
    return ok, err
end

--- Screen.Move(x1, y1, x2, y2, x3, y3 [, char [, attr]])
-- Moves the block between two corners so its top-left lands at (x3, y3),
-- blanking what it uncovers with `char` (default space) and `attr`.
function Screen.Move(x1, y1, x2, y2, x3, y3, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenMove(x, y, w, h, x3, y3, char or 32, attr or 0)
end

--- Screen.Scroll(x1, y1, x2, y2, dx, dy [, char [, attr]])
-- Shifts the contents of a region by (dx, dy) cells; the cells it
-- uncovers are filled with `char` (default space) and `attr`.
function Screen.Scroll(x1, y1, x2, y2, dx, dy, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenScroll(x, y, w, h, dx, dy, char or 32, attr or 0)
end

--- Screen.ScrollUp([lines [, char [, attr]]])
-- Scrolls the whole screen up by `lines` (default 1).
function Screen.ScrollUp(lines, char, attr)
    return ScreenScroll(0, 0, Screen.COLS, Screen.ROWS, 0, -(lines or 1), char or 32, attr or 0)
end

--- Screen.LoadImage(path, x, y [, w, h])
-- Draws an image file from the card at (x, y). Reserved: the OS loader
-- is not available yet, so this returns nil and a message for now.
function Screen.LoadImage(path, x, y, w, h)
    return ScreenLoadImage(path, x, y, w, h)
end

-- ==== sdk: overlay (read-only; unused functions stripped) ====

-- SDK: Overlay
-- Summary: Dialogs, menus and pop-ups on the overlay layer, over the base screen.
-- Namespaces: Overlay
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- The overlay is one layer composited over the base: cells you write
-- show, cells you never touch stay transparent, and Overlay.Clear()
-- hides everything again. Region calls take inclusive corners
-- (x1, y1, x2, y2).

Overlay = Overlay or {}
Overlay.COLS = 40
Overlay.ROWS = 30
Overlay.SINGLE = 1
Overlay.DOUBLE = 2
Overlay.INVERT = 0x80

local function region(x1, y1, x2, y2)
    if x2 < x1 then x1, x2 = x2, x1 end
    if y2 < y1 then y1, y2 = y2, y1 end
    return x1, y1, x2 - x1 + 1, y2 - y1 + 1
end

--- Overlay.OutText(x, y, text [, attr])
-- Writes a string on the overlay from (x, y), wrapping at the right edge.
function Overlay.OutText(x, y, text, attr)
    return OverlayWrite(x, y, tostring(text), attr or 0)
end

--- Overlay.Window(x1, y1, x2, y2 [, title [, style [, attr]]])
-- A blank window on the overlay: inside cleared, frame, optional title.
function Overlay.Window(x1, y1, x2, y2, title, style, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    attr = attr or 0
    OverlayFill(x, y, w, h, 32, attr)
    local ok, err = OverlayBox(x, y, w, h, style or 1, attr)
    if ok and title and #tostring(title) > 0 then
        local label = " " .. tostring(title) .. " "
        local tx = x + (w - #label) // 2
        if tx < x + 1 then tx = x + 1 end
        OverlayWrite(tx, y, label:sub(1, w - 2), attr)
    end
    return ok, err
end

--- Overlay.Dialog(title, lines [, attr [, style]])
-- A centred dialog: a window sized to fit `lines` (a string or an array
-- of strings) with `title` on its frame. Returns the window's corners
-- (x1, y1, x2, y2) so buttons or a cursor can be placed inside it.
function Overlay.Dialog(title, lines, attr, style)
    if type(lines) == "string" then
        lines = { lines }
    end
    attr = attr or Overlay.INVERT
    local width = #tostring(title or "") + 2
    for _, line in ipairs(lines) do
        if #tostring(line) > width then width = #tostring(line) end
    end
    width = width + 4
    if width > Overlay.COLS then width = Overlay.COLS end
    local height = #lines + 4
    if height > Overlay.ROWS then height = Overlay.ROWS end
    local x1 = (Overlay.COLS - width) // 2
    local y1 = (Overlay.ROWS - height) // 2
    local x2, y2 = x1 + width - 1, y1 + height - 1
    Overlay.Window(x1, y1, x2, y2, title, style or Overlay.DOUBLE, attr)
    for i, line in ipairs(lines) do
        if y1 + 1 + i < y2 then
            OverlayWrite(x1 + 2, y1 + 1 + i, tostring(line):sub(1, width - 4), attr)
        end
    end
    return x1, y1, x2, y2
end

-- ==== sdk: sound (read-only; unused functions stripped) ====

-- SDK: Sound
-- Summary: Tones, beeps and effects without defining instruments first; music playback.
-- Namespaces: Sound, Music
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- The OS sound engine is complete and runs in the simulator; the
-- product board's audio output is not wired yet, so on hardware these
-- calls succeed silently until it is.

Sound = Sound or {}
Music = Music or {}

-- Instrument ids this framework reserves at the top of the 0..31 range,
-- defined on first use so programs that only use Sound.Play pay nothing.
local TONE_ID = 31
local NOISE_ID = 30
local tone_defined = false
local noise_defined = false

local function ensure_tone()
    if not tone_defined then
        SoundDefine(TONE_ID, { wave = "square", duty = 8, attack = 2, decay = 10,
                               sustain = 220, release = 30 })
        tone_defined = true
    end
end

-- MIDI note number nearest to a frequency in Hz (A4 = 440 = 69).
local function note_for_hz(hz)
    if not hz or hz <= 0 then return 69 end
    local n = math.floor(69 + 12 * math.log(hz / 440, 2) + 0.5)
    if n < 0 then n = 0 end
    if n > 127 then n = 127 end
    return n
end

--- Sound.Tone(hz, ms [, volume])
-- Plays a square-wave tone at (nearest note to) `hz` for `ms`
-- milliseconds; `volume` 0..255 (default 255). Returns the voice id.
function Sound.Tone(hz, ms, volume)
    ensure_tone()
    return SoundPlay(TONE_ID, note_for_hz(hz), ms or 100, volume or 255)
end

--- Sound.Beep([ms])
-- A short 880 Hz beep (default 80 ms).
function Sound.Beep(ms)
    ensure_tone()
    return SoundPlay(TONE_ID, 81, ms or 80, 255)
end

-- ==== sdk: input (read-only; unused functions stripped) ====

-- SDK: Input
-- Summary: Keyboard and joystick callbacks by key or action, plus key-code names.
-- Namespaces: Input, Input.Keyboard, Input.Joystick
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- Callbacks install themselves into the program's on_keypress /
-- on_control hooks the first time one is registered, chaining to any
-- hook the program defined itself. Register them in setup().

Input = Input or {}
Input.Keyboard = Input.Keyboard or {}
Input.Joystick = Input.Joystick or {}

-- Key codes (see lua.md): ASCII for printable keys, these for the rest.
Input.KEY_RETURN = 13
Input.KEY_ESCAPE = 27
Input.KEY_BACKSPACE = 8
Input.KEY_DELETE = 127
Input.KEY_TAB = 9
Input.KEY_SPACE = 32
Input.KEY_UP = 128
Input.KEY_DOWN = 129
Input.KEY_LEFT = 130
Input.KEY_RIGHT = 131
Input.KEY_F1 = 132
Input.KEY_F2 = 133
Input.KEY_F3 = 134
Input.KEY_F4 = 135
Input.KEY_F5 = 136
Input.KEY_F6 = 137
Input.KEY_F7 = 138
Input.KEY_HOME = 139
Input.KEY_RUNSTOP = 140

local key_handlers = {}     -- key code -> fn
local key_any_handler = nil
local keyboard_installed = false

local joy_handlers = {}     -- "port:action" -> fn
local joy_state = { 0, 0 }  -- last seen direction bits per port (1-based)
local joystick_installed = false
local JOY_ACTIONS = { "up", "down", "left", "right", "fire" }

-- A key argument as a code: numbers pass through, one-character strings
-- become their byte, "any" stays a word.
local function key_code(key)
    if type(key) == "string" then
        if key == "any" then return "any" end
        return key:byte(1)
    end
    return key
end

local function install_keyboard()
    if keyboard_installed then return end
    keyboard_installed = true
    local previous = on_keypress
    on_keypress = function(key, shift, ctrl, cbm, restore)
        local fn = key_handlers[key]
        if fn then fn(key, shift, ctrl, cbm, restore) end
        if key_any_handler then key_any_handler(key, shift, ctrl, cbm, restore) end
        if previous then previous(key, shift, ctrl, cbm, restore) end
    end
end

local function install_joystick()
    if joystick_installed then return end
    joystick_installed = true
    local previous = on_control
    on_control = function(index, up, down, left, right, fire)
        local port = index + 1
        local now = { up = up, down = down, left = left, right = right, fire = fire }
        local was = joy_state[port] or {}
        for _, action in ipairs(JOY_ACTIONS) do
            if now[action] ~= (was[action] or false) then
                local fn = joy_handlers[port .. ":" .. action]
                if fn then fn(port, action, now[action]) end
                local any = joy_handlers[port .. ":any"]
                if any then any(port, action, now[action]) end
            end
        end
        joy_state[port] = now
        if previous then previous(index, up, down, left, right, fire) end
    end
end

--- Input.Keyboard.Callback(key, fn)
-- Calls fn(key, shift, ctrl, cbm, restore) when `key` is pressed: a key
-- code, a one-character string such as "a", or "any" for every key.
function Input.Keyboard.Callback(key, fn)
    install_keyboard()
    local code = key_code(key)
    if code == "any" then
        key_any_handler = fn
    else
        key_handlers[code] = fn
    end
    return true
end

--- Input.Joystick.Callback(port, action, fn)
-- Calls fn(port, action, pressed) when joystick `port` (1 or 2) changes
-- `action`: "up", "down", "left", "right", "fire" or "any".
function Input.Joystick.Callback(port, action, fn)
    install_joystick()
    joy_handlers[port .. ":" .. action] = fn
    return true
end

--- Input.Keyboard.Name(key)
-- A readable name for a key code: "RETURN", "F1", "a" and so on.
function Input.Keyboard.Name(key)
    local names = {
        [13] = "RETURN", [27] = "ESCAPE", [8] = "BACKSPACE", [127] = "DELETE",
        [9] = "TAB", [32] = "SPACE", [128] = "UP", [129] = "DOWN",
        [130] = "LEFT", [131] = "RIGHT", [132] = "F1", [133] = "F2",
        [134] = "F3", [135] = "F4", [136] = "F5", [137] = "F6", [138] = "F7",
        [139] = "HOME", [140] = "RUN/STOP",
    }
    if names[key] then return names[key] end
    if key and key >= 33 and key < 127 then return string.char(key) end
    return tostring(key)
end

-- ==== component: header (snippet) ====

-- demo.lua — the frameworks (Screen, Overlay, Sound, Input) in action.
--
-- Launch from the shell:  demo
--
-- Draws a window with the Screen framework, moves and scrolls blocks,
-- pops an Overlay dialog, beeps, and waits for a key through
-- Input.Keyboard.Callback. Every call's result is recorded and written
-- to /data/demo-selftest.txt ("ok name" per line), so the same program
-- doubles as the frameworks' integration test in the simulator:
--
--   spicomputer_sim --boot apps/demo.app/app.prg --headless --type 'k'
--
-- The built program keeps only the framework functions this code uses;
-- compare the generated demo.lua with the framework files to see the
-- stripping at work.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/demo` from the workspace root.

-- ==== component: main (lua) ====

local results = {}

local function check(name, ok, err)
    if ok then
        results[#results + 1] = "ok " .. name
    else
        results[#results + 1] = "FAIL " .. name .. ": " .. tostring(err)
    end
    return ok
end

local function save()
    fs.writeall("/data/demo-selftest.txt", table.concat(results, "\n") .. "\n")
end

function setup()
    check("mode", Screen.Mode(1))
    check("window", Screen.Window(0, 0, 39, 29, "SDK DEMO", Screen.DOUBLE))
    check("center", Screen.CenterText(2, "Screen.CenterText(2, ...)"))
    check("right", Screen.RightText(3, "RightText " .. string.char(16), 0x02))
    check("outtext", Screen.OutText(2, 5, "Fill, then Move to the right:", 0x02))
    check("fill", Screen.Fill(2, 7, 11, 9, 219))
    check("move", Screen.Move(2, 7, 11, 9, 24, 7))
    check("outtext2", Screen.OutText(2, 11, "Scroll region down 1:", 0x02))
    check("fill2", Screen.Fill(2, 13, 37, 13, 177))
    check("scroll", Screen.Scroll(2, 13, 37, 15, 0, 1))
    check("hline", Screen.HLine(2, 37, 17))
    check("vline", Screen.VLine(20, 18, 21))
    check("printf", Screen.Printf(2, 19, "Printf: %d + %d = %d", 2, 3, 2 + 3))
    check("clean", Screen.Clean(22, 18, 37, 21))
    check("box", Screen.Box(22, 18, 37, 21, Screen.SINGLE, 0x03))
    check("scrollup", Screen.ScrollUp(0))
    local ok, err = Screen.LoadImage("logo.bmp", 0, 0)
    check("loadimage-reserved", ok == nil and err ~= nil, "expected nil, err")
    local x1, y1, x2, y2 = Overlay.Dialog("HELLO", { "Overlay.Dialog over the screen", "press any key" })
    check("dialog", x1 ~= nil and x2 > x1 and y2 > y1, "no corners")
    check("overlay-text", Overlay.OutText(x1 + 2, y2 - 1, "[ OK ]", Overlay.INVERT))
    local voice = Sound.Beep()
    check("beep", type(voice) == "number", tostring(voice))
    check("tone", type(Sound.Tone(440, 50, 128)) == "number", "no voice")
    check("keyname", Input.Keyboard.Name(Input.KEY_RETURN) == "RETURN", Input.Keyboard.Name(13))
    Input.Keyboard.Callback("any", function(key)
        results[#results + 1] = "key " .. Input.Keyboard.Name(key)
        save()
        ExitProgram()
    end)
    Input.Joystick.Callback(1, "fire", function(port, action, pressed)
        results[#results + 1] = "joystick " .. port .. " " .. action .. " " .. tostring(pressed)
    end)
    save()
end

function tick()
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
