-- ================================================================
-- editor
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-12T06:19:01Z from components:
--   snippet header
--   lua     document
--   lua     screen
--   lua     edits
--   lua     commands
--   lua     input
--   lua     main
-- ================================================================

-- ==== component: header (snippet) ====

-- editor.lua — SPIComputer OS text editor.
--
-- Launch from the shell:  editor <file>   (or: run editor <file>).
-- The file name arrives as args[1] (and as the chunk's vararg).
--
-- The file is edited entirely in RAM (array of lines) and written back
-- on save, so insertion is fast and the SD card only sees whole-file
-- writes. Files are capped at 128 KB by fs.readall.
--
-- Keys:
--   cursor keys   move
--   F1/F2/F3/F4   help/file/edit/options menus
--   Ctrl+F/E/O/H  open file/edit/options/help menus
--   Return        split the line
--   Backspace     delete before cursor
--   Shift+Del     insert a space (C64 INST semantics)
--   Forward del   delete at cursor
--   Home          start of line
--   Ctrl+S        save
--   Ctrl+Q        quit (asks if the buffer is dirty)
--   printable     insert (shift is already applied by the OS)
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/editor` from the workspace root. The generated editor.lua is
-- written to the parent folder.

local filename = ... or "untitled.txt"
if filename:sub(1, 6) ~= "/data/" then
    filename = "/data/" .. filename:gsub("^/+", "")
end

local W, H = 40, 29        -- text area; screen line 29 is the status bar
local editor_wide = false
local lines = {}
local cx, cy = 0, 1        -- cursor: column (0-based), line (1-based)
local scroll_y = 0         -- top visible line (0-based index)
local dirty = false
local quit_confirm = false
local cursor_on = true
local menu_open = false
local menu_top = 1
local menu_item = 1
local dialog_open = false
local dialog_kind = ""
local dialog_text = ""
local dialog_cursor = 0
local menu_defs = {
    {name = "FILE", items = {"Save", "Go to line", "Quit"}},
    {name = "EDIT", items = {"Top of file", "Bottom of file", "Delete line"}},
    {name = "OPTIONS", items = {"Toggle 40/80", "Toggle cursor", "Clear menu"}},
    {name = "HELP", items = {"Keyboard help"}},
}

-- ==== component: document (lua) ====

-- Document: the RAM buffer is an array of lines; the SD card only sees
-- whole-file reads and writes.

local function load_content(content)
    if content == "" then return { "" } end
    local base = content
    if content:sub(-1) ~= "\n" then base = content .. "\n" end
    local t, i = {}, 0
    for l in base:gmatch("([^\n]*)\n") do i = i + 1; t[i] = l end
    return t
end

-- ==== component: screen (lua) ====

-- Screen: 29 text lines plus an inverted status bar (line 29), and the
-- blinking cursor cell.

local function draw_cursor()
    local ly = cy - 1 - scroll_y
    if ly >= 0 and ly < H and cx < W then
        local ch = (lines[cy] or ""):byte(cx + 1) or 32
        ScreenOut(cx, ly, ch, cursor_on and 0x80 or 0)
    end
end

local function draw_status()
    local s = string.format("%s L%d C%d%s", filename, cy, cx + 1,
                            dirty and " *" or "")
    if quit_confirm then s = "save? (y/n)  " .. s end
    for c = 1, W do
        ScreenOut(c - 1, H, s:byte(c) or 32, 0x80)
    end
end

local function fill_rect(x, y, w, h, attr)
    for row = y, y + h - 1 do
        for col = x, x + w - 1 do
            ScreenOut(col, row, 32, attr)
        end
    end
end

local function draw_string(x, y, text, attr)
    for i = 1, #text do
        if x + i - 1 < W and y >= 0 and y <= H then
            ScreenOut(x + i - 1, y, text:byte(i), attr)
        end
    end
end

local function menu_x(index)
    local x = 0
    for i = 1, index - 1 do
        x = x + #menu_defs[i].name + 2
    end
    return x
end

local function menu_width(menu)
    local width = #menu.name + 2
    for _, item in ipairs(menu.items) do
        width = math.max(width, #item + 2)
    end
    return width
end

local function draw_menu_layer()
    ScreenZOrder(1)
    ScreenClear(32)
    for i, menu in ipairs(menu_defs) do
        local x = menu_x(i)
        local attr = i == menu_top and 0x80 or 0
        for col = x, x + #menu.name + 1 do
            ScreenOut(col, 0, 32, attr)
        end
        draw_string(x + 1, 0, menu.name, attr)
    end
    if menu_open then
        local menu = menu_defs[menu_top]
        local x = menu_x(menu_top)
        local width = menu_width(menu)
        fill_rect(x, 1, width, #menu.items, 0)
        for i, item in ipairs(menu.items) do
            local attr = i == menu_item and 0x80 or 0
            for col = x, x + width - 1 do
                ScreenOut(col, i, 32, attr)
            end
            draw_string(x + 1, i, item, attr)
        end
    end
end

local function draw_dialog_layer()
    ScreenZOrder(2)
    ScreenClear(32)
    if not dialog_open then return end
    if dialog_kind == "goto" then
        local x = math.floor((W - 26) / 2)
        fill_rect(x, 10, 26, 5, 0)
        draw_string(x + 2, 11, "GO TO LINE", 0)
        draw_string(x + 2, 13, dialog_text, 0x80)
        ScreenOut(x + 2 + #dialog_text, 13, 32, 0x80)
        draw_string(x + 2, 14, "ENTER ACCEPT  ESC CANCEL", 0)
    elseif dialog_kind == "help" then
        local x = math.floor((W - 36) / 2)
        fill_rect(x, 4, 36, 21, 0)
        draw_string(x + 13, 5, "EDITOR HELP", 0x80)
        local help = {
            "CTRL+F        FILE MENU",
            "CTRL+E        EDIT MENU",
            "CTRL+O        OPTIONS MENU",
            "CTRL+H        HELP MENU",
            "OPTIONS       TOGGLE 40/80 WIDTH",
            "ARROWS        MOVE / NAVIGATE",
            "ENTER         SELECT MENU ITEM",
            "ESC           CLOSE MENU",
            "CTRL+S        SAVE",
            "CTRL+Q        QUIT",
        }
        for i, line in ipairs(help) do
            draw_string(x + 2, 7 + i, line, 0)
        end
        draw_string(x + 6, 20, "PRESS ESC TO CLOSE", 0x80)
    end
end

local function draw_overlays()
    draw_menu_layer()
    draw_dialog_layer()
    ScreenZOrder(0)
end

local function draw()
    ScreenZOrder(0)
    ScreenClear(32)
    for r = 0, H - 1 do
        local li = lines[scroll_y + r + 1]
        if li then
            for c = 1, W do
                local b = li:byte(c)
                if b then ScreenOut(c - 1, r, b, 0) end
            end
        end
    end
    draw_cursor()
    draw_status()
    draw_overlays()
end

-- ==== component: edits (lua) ====

-- Editing operations: each mutates the buffer and redraws.

local function insert_char(ch)
    local line = lines[cy]
    lines[cy] = line:sub(1, cx) .. ch .. line:sub(cx + 1)
    cx = cx + 1
    dirty = true
    draw()
end

local function backspace()
    if cx > 0 then
        local line = lines[cy]
        lines[cy] = line:sub(1, cx - 1) .. line:sub(cx + 1)
        cx = cx - 1
    elseif cy > 1 then
        local prev = lines[cy - 1]
        lines[cy - 1] = prev .. lines[cy]
        table.remove(lines, cy)
        cx = #prev
        cy = cy - 1
    end
    dirty = true
    draw()
end

local function fwd_delete()
    local line = lines[cy]
    if cx < #line then
        lines[cy] = line:sub(1, cx) .. line:sub(cx + 2)
    elseif cy < #lines then
        lines[cy] = line .. lines[cy + 1]
        table.remove(lines, cy + 1)
    end
    dirty = true
    draw()
end

local function insert_newline()
    local line = lines[cy]
    lines[cy] = line:sub(1, cx)
    table.insert(lines, cy + 1, line:sub(cx + 1))
    cx = 0
    cy = cy + 1
    if cy - 1 >= scroll_y + H then scroll_y = scroll_y + 1 end
    dirty = true
    draw()
end

local function move(dx, dy)
    cx = cx + dx
    cy = cy + dy
    cx = math.max(0, math.min(cx, W - 1))
    cy = math.max(1, math.min(cy, #lines))
    local ll = #lines[cy]
    if cx > ll then cx = ll end
    if cy - 1 < scroll_y then
        scroll_y = cy - 1
    elseif cy - 1 >= scroll_y + H then
        scroll_y = cy - H + 1
    end
    draw()
end

-- ==== component: commands (lua) ====

-- File commands: save the RAM buffer back to the SD card, quit.

local function save()
    local ok, err = fs.writeall(filename, table.concat(lines, "\n") .. "\n")
    if ok then
        dirty = false
    else
        print("save failed: " .. tostring(err))
    end
    draw()
end

local function quit()
    ExitProgram()
end

local function close_menus()
    menu_open = false
    dialog_open = false
    dialog_kind = ""
    dialog_text = ""
    draw()
end

local function open_menu(index)
    dialog_open = false
    menu_open = true
    menu_top = index
    menu_item = 1
    draw()
end

local function open_dialog(kind)
    menu_open = false
    dialog_open = true
    dialog_kind = kind
    dialog_text = ""
    dialog_cursor = 0
    draw()
end

local function toggle_width()
    editor_wide = not editor_wide
    if editor_wide then
        W, H = 80, 59
        ScreenMode(3)
    else
        W, H = 40, 29
        ScreenMode(1)
    end
    cx = math.min(cx, W - 1)
    scroll_y = math.max(0, math.min(scroll_y, math.max(0, #lines - H)))
    ScreenPalette(0, 0, 0, 160)
    ScreenPalette(1, 255, 255, 255)
    draw()
end

local function select_menu_item()
    local menu = menu_defs[menu_top]
    local item = menu.items[menu_item]
    if menu_top == 1 and item == "Save" then
        save()
        close_menus()
    elseif menu_top == 1 and item == "Go to line" then
        open_dialog("goto")
    elseif menu_top == 1 and item == "Quit" then
        close_menus()
        if dirty then
            quit_confirm = true
            draw()
        else
            quit()
        end
    elseif menu_top == 2 and item == "Top of file" then
        cy = 1
        cx = 0
        scroll_y = 0
        close_menus()
    elseif menu_top == 2 and item == "Bottom of file" then
        cy = #lines
        cx = 0
        scroll_y = math.max(0, cy - H)
        close_menus()
    elseif menu_top == 2 and item == "Delete line" then
        if #lines > 1 then
            table.remove(lines, cy)
            cy = math.min(cy, #lines)
            cx = math.min(cx, #(lines[cy] or ""))
            dirty = true
        end
        close_menus()
    elseif menu_top == 3 and item == "Toggle 40/80" then
        toggle_width()
        close_menus()
    elseif menu_top == 3 and item == "Toggle cursor" then
        cursor_on = not cursor_on
        close_menus()
    elseif menu_top == 3 and item == "Clear menu" then
        close_menus()
    elseif menu_top == 4 and item == "Keyboard help" then
        open_dialog("help")
    end
end

local function handle_menu_key(ev)
    local k = ev.key
    if k == 27 then
        close_menus()
    elseif k == 128 then
        if menu_open then
            menu_item = (menu_item - 2) % #menu_defs[menu_top].items + 1
            draw()
        end
    elseif k == 129 then
        if menu_open then
            menu_item = menu_item % #menu_defs[menu_top].items + 1
            draw()
        end
    elseif k == 130 and menu_open then
        menu_top = (menu_top - 2) % #menu_defs + 1
        menu_item = 1
        draw()
    elseif k == 131 and menu_open then
        menu_top = menu_top % #menu_defs + 1
        menu_item = 1
        draw()
    elseif k == 13 and menu_open then
        select_menu_item()
    end
end

local function handle_dialog_key(ev)
    local k = ev.key
    if k == 27 then
        close_menus()
    elseif dialog_kind == "help" then
        if k == 13 then close_menus() end
    elseif dialog_kind == "goto" then
        if k == 13 then
            local target = tonumber(dialog_text)
            if target then
                cy = math.max(1, math.min(math.floor(target), #lines))
                cx = 0
                if cy - 1 < scroll_y then
                    scroll_y = cy - 1
                elseif cy - 1 >= scroll_y + H then
                    scroll_y = cy - H + 1
                end
            end
            close_menus()
        elseif k == 8 then
            dialog_text = dialog_text:sub(1, -2)
            draw()
        elseif k >= 48 and k <= 57 and #dialog_text < 5 then
            dialog_text = dialog_text .. string.char(k)
            draw()
        end
    end
end

-- ==== component: input (lua) ====

-- Keyboard: cursor keys, editing keys, menu shortcuts and dialogs.

local function ctrl_down(mods)
    return math.floor(mods / 2) % 2 == 1
end

local function handle_key(ev)
    if dialog_open then
        handle_dialog_key(ev)
        return
    end
    if menu_open then
        handle_menu_key(ev)
        return
    end
    if quit_confirm then
        if ev.key == 121 then save(); quit()
        elseif ev.key == 110 then quit()
        else quit_confirm = false; draw_status() end
        return
    end

    local k = ev.key
    if ctrl_down(ev.mods) then
        if k == 102 then open_menu(1)
        elseif k == 101 then open_menu(2)
        elseif k == 111 then open_menu(3)
        elseif k == 104 then open_dialog("help")
        elseif k == 115 then save()
        elseif k == 113 then
            if dirty then quit_confirm = true; draw() else quit() end
        end
        return
    end

    if k == 132 then open_dialog("help")
    elseif k == 133 then open_menu(1)
    elseif k == 134 then open_menu(2)
    elseif k == 135 then open_menu(3)
    elseif k == 128 then move(0, -1)
    elseif k == 129 then move(0, 1)
    elseif k == 130 then move(-1, 0)
    elseif k == 131 then move(1, 0)
    elseif k == 13 then insert_newline()
    elseif k == 8 then
        if ev.mods % 2 == 1 then insert_char(" ") else backspace() end
    elseif k == 127 then fwd_delete()
    elseif k == 19 then save()
    elseif k == 17 then
        if dirty then quit_confirm = true; draw() else quit() end
    elseif k == 139 then cx = 0; draw()
    elseif k >= 32 and k < 128 then insert_char(string.char(k))
    end
end

-- ==== component: main (lua) ====

-- Entry points: load the file, blink the cursor, pump input.

function setup()
    ScreenMode(1)
    ScreenPalette(0, 0, 0, 160)
    ScreenPalette(1, 255, 255, 255)
    local content, err = fs.readall(filename)
    if content then
        lines = load_content(content)
    else
        lines = { "" }
        print("new file: " .. tostring(err))
    end
    TimerCreate(function()
        cursor_on = not cursor_on
        draw()
    end, 500)
    draw()
end

function tick()
    while true do
        local ev = InputPoll()
        if not ev then break end
        if ev.type == "key" and ev.pressed == 1 then handle_key(ev) end
    end
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
