import Foundation

/// Completion vocabulary for the code editor: Lua keywords and standard
/// library plus the SPIComputer OS modules (see lua.md).
public enum LuaCompletion {
    public static let keywords: [String] = [
        "and", "break", "do", "else", "elseif", "end", "false", "for",
        "function", "goto", "if", "in", "local", "nil", "not", "or",
        "repeat", "return", "then", "true", "until", "while",
    ]

    public static let builtins: [String] = [
        "assert", "collectgarbage", "dofile", "error", "getmetatable",
        "ipairs", "loadfile", "next", "pairs", "pcall", "print", "rawequal",
        "rawget", "rawlen", "rawset", "require", "select", "setmetatable",
        "tonumber", "tostring", "type", "xpcall",
        "coroutine.create", "coroutine.isyieldable", "coroutine.resume",
        "coroutine.running", "coroutine.status", "coroutine.wrap",
        "coroutine.yield",
        "math.abs", "math.ceil", "math.floor", "math.fmod", "math.huge",
        "math.max", "math.min", "math.pi", "math.random", "math.randomseed",
        "math.sqrt",
        "package.loaded", "package.path", "package.preload",
        "string.byte", "string.char", "string.find", "string.format",
        "string.gmatch", "string.gsub", "string.len", "string.lower",
        "string.match", "string.rep", "string.reverse", "string.sub",
        "string.upper",
        "table.concat", "table.insert", "table.move", "table.pack",
        "table.remove", "table.sort", "table.unpack",
        "utf8.char", "utf8.codepoint", "utf8.codes", "utf8.len", "utf8.offset",
    ]

    public static let spiComputer: [String] = [
        // System
        "TimeNow", "Pid", "ExitProgram", "Launch", "Execute", "ExecuteString", "Compile",
        "UtilityResult", "UtilityPoll", "pid",
        "TimerCreate", "TimerStop",
        "InputPoll", "InputControl",
        // Display
        "ScreenMode", "ScreenOut", "ScreenAttr", "ScreenDefineTile",
        "ScreenPalette", "ScreenPaletteSet", "ScreenClear", "ScreenPlot",
        "ScreenBox", "ScreenFill", "ScreenFillAttr", "ScreenCopy", "ScreenMove",
        "ScreenScroll", "ScreenWrite", "ScreenWriteAttr", "ScreenLoadImage",
        "OverlayOut", "OverlayAttr", "OverlayClear", "OverlayBox", "OverlayFill",
        "OverlayFillAttr", "OverlayCopy", "OverlayMove", "OverlayScroll",
        "OverlayWrite", "OverlayWriteAttr",
        "ScreenPixelRect", "ScreenPixelLine", "ScreenPixelCircle", "ScreenPixelScroll",
        "ScreenBlit", "ScreenPixelText",
        // Sound
        "SoundDefine", "SoundLoad", "SoundPlay", "SoundStop", "SoundStopAll",
        "SoundVolume", "MusicDefine", "MusicPlay", "MusicStop", "MusicPlaying",
        // Filesystem
        "fs.open", "fs.ls", "fs.stat", "fs.exists", "fs.mkdir", "fs.remove",
        "fs.rename", "fs.free", "fs.ready", "fs.mount", "fs.readall",
        "fs.writeall",
        // Generated by the IDE
        "ApplyAssets",
    ]

    public static let all: [String] = keywords + builtins + spiComputer

    /// Completions whose text starts with `prefix`, including functions
    /// defined in `source` (the file being edited) and anywhere else in
    /// the project via `definedFunctions`, and the frameworks' `constants`. Locally defined signatures win
    /// over the built-in tables, each name appears once, and shorter
    /// names sort first so plain names win over members.
    public static func items(
        _ prefix: String,
        in source: String,
        including definedFunctions: [LuaSignature] = [],
        constants: [String] = []
    ) -> [CompletionItem] {
        var signatures: [String: LuaSignature] = [:]
        for signature in definedFunctions {
            signatures[signature.name] = signature
        }
        // The edited file's own definitions are read last and win.
        for signature in LuaFunctionIndex.functions(in: source) {
            signatures[signature.name] = signature
        }

        var names = all
        var known = Set(all)
        for name in signatures.keys.sorted() where known.insert(name).inserted {
            names.append(name)
        }
        // Framework constants complete like names, without a parameter list.
        for name in constants where known.insert(name).inserted {
            names.append(name)
        }
        let matched = prefix.isEmpty ? names : names.filter { $0.hasPrefix(prefix) }
        return matched
            .sorted {
                if $0.count != $1.count { return $0.count < $1.count }
                return $0 < $1
            }
            .map { name in
                let signature = signatures[name] ?? LuaSignatures.signature(for: name)
                return CompletionItem(
                    name: name,
                    detail: signature.map { "(\($0.parameters.joined(separator: ", ")))" })
            }
    }

    /// Completion names only, for callers that just filter names.
    public static func matches(_ prefix: String) -> [String] {
        items(prefix, in: "").map(\.name)
    }
}
