import Foundation

/// Completion vocabulary for the code editor: Lua keywords and standard
/// library plus the SPIComputer OS modules (see lua.md).
public enum LuaCompletion {
    public static let keywords: [String] = [
        "and", "break", "do", "else", "elseif", "end", "false", "for",
        "function", "goto", "if", "in", "local", "nil", "not", "or",
        "repeat", "return", "then", "true", "until", "while",
    ]

    public static let builtins: [String] = [
        "assert", "collectgarbage", "dofile", "error", "getmetatable",
        "ipairs", "loadfile", "next", "pairs", "pcall", "print", "rawequal",
        "rawget", "rawlen", "rawset", "require", "select", "setmetatable",
        "tonumber", "tostring", "type", "xpcall",
        "coroutine.create", "coroutine.isyieldable", "coroutine.resume",
        "coroutine.running", "coroutine.status", "coroutine.wrap",
        "coroutine.yield",
        "math.abs", "math.ceil", "math.floor", "math.fmod", "math.huge",
        "math.max", "math.min", "math.pi", "math.random", "math.randomseed",
        "math.sqrt",
        "package.loaded", "package.path", "package.preload",
        "string.byte", "string.char", "string.find", "string.format",
        "string.gmatch", "string.gsub", "string.len", "string.lower",
        "string.match", "string.rep", "string.reverse", "string.sub",
        "string.upper",
        "table.concat", "table.insert", "table.move", "table.pack",
        "table.remove", "table.sort", "table.unpack",
        "utf8.char", "utf8.codepoint", "utf8.codes", "utf8.len", "utf8.offset",
    ]

    public static let spiComputer: [String] = [
        // System
        "TimeNow", "Pid", "ExitProgram", "Launch", "Execute", "ExecuteString",
        "UtilityResult", "UtilityPoll", "pid",
        "TimerCreate", "TimerStop",
        "InputPoll", "InputControl",
        // Display
        "ScreenMode", "ScreenZOrder", "ScreenOut", "ScreenAttr", "ScreenDefineTile",
        "ScreenPalette", "ScreenPaletteSet", "ScreenClear", "ScreenPlot",
        // Sound
        "SoundDefine", "SoundLoad", "SoundPlay", "SoundStop", "SoundStopAll",
        "SoundVolume", "MusicDefine", "MusicPlay", "MusicStop", "MusicPlaying",
        // Filesystem
        "fs.open", "fs.ls", "fs.stat", "fs.exists", "fs.mkdir", "fs.remove",
        "fs.rename", "fs.free", "fs.ready", "fs.mount", "fs.readall",
        "fs.writeall",
        // Generated by the IDE
        "ApplyAssets",
    ]

    public static let all: [String] = keywords + builtins + spiComputer

    /// Completions whose text starts with `prefix` (case-sensitive, as Lua
    /// is). Shorter names sort first so plain names win over members.
    public static func matches(_ prefix: String) -> [String] {
        guard !prefix.isEmpty else { return all }
        return all
            .filter { $0.hasPrefix(prefix) }
            .sorted {
                if $0.count != $1.count { return $0.count < $1.count }
                return $0 < $1
            }
    }
}
