import Foundation

/// One function signature used by the editor's parameter help.
public struct LuaSignature: Equatable, Sendable {
    public let name: String
    public let parameters: [String]

    public init(name: String, parameters: [String]) {
        self.name = name
        self.parameters = parameters
    }

    /// `name(param, param, ...)`.
    public var display: String {
        "\(name)(\(parameters.joined(separator: ", ")))"
    }

    /// True when the signature ends in `...` (extra arguments are valid).
    public var variadic: Bool {
        parameters.last?.contains("...") ?? false
    }

    /// The parameter to highlight for a 0-based argument index, or nil
    /// when the call has more arguments than the signature declares.
    public func parameterIndex(forArgument index: Int) -> Int? {
        guard index >= 0 else { return nil }
        if index < parameters.count {
            return index
        }
        return variadic ? parameters.count - 1 : nil
    }
}

/// Signatures for the SPIComputer OS API (see lua.md) and the Lua
/// standard library, keyed by the name as written at the call site.
/// File methods are keyed by the part from the colon (":read"), so any
/// receiver (`f:read`, `file:read`) matches.
public enum LuaSignatures {
    public static func signature(for name: String) -> LuaSignature? {
        table[name]
    }

    /// The indexed subset shown in parameter help. Ordered by the docs.
    public static let table: [String: LuaSignature] = {
        var result: [String: LuaSignature] = [:]
        func add(_ name: String, _ parameters: String...) {
            result[name] = LuaSignature(name: name, parameters: parameters)
        }

        // System
        add("TimeNow")
        add("Pid")
        add("ExitProgram")
        add("Launch", "path", "[arg]")
        add("TimerCreate", "fn", "interval_ms", "[oneshot]")
        add("TimerStop", "id")
        add("InputPoll")
        add("InputControl", "n")

        // Display
        add("ScreenMode", "mode")
        add("ScreenOut", "x", "y", "char", "[attr]")
        add("ScreenAttr", "x", "y", "flags")
        add("ScreenDefineTile", "index", "bytes")
        add("ScreenPalette", "i", "r", "g", "b")
        add("ScreenPaletteSet", "t")
        add("ScreenClear", "[char]")
        add("ScreenPlot", "x", "y", "colour")

        // Sound and music
        add("SoundDefine", "id", "spec")
        add("SoundLoad", "path")
        add("SoundPlay", "sound", "[note]", "[dur_ms]", "[vol]", "[pan]")
        add("SoundStop", "[voice]")
        add("SoundStopAll")
        add("SoundVolume", "v")
        add("MusicDefine", "name", "spec")
        add("MusicPlay", "name", "[loop]")
        add("MusicStop")
        add("MusicPlaying")

        // Filesystem
        add("fs.open", "path", "[mode]")
        add("fs.ls", "[path]")
        add("fs.stat", "path")
        add("fs.exists", "path")
        add("fs.mkdir", "path")
        add("fs.remove", "path")
        add("fs.rename", "old", "new")
        add("fs.free")
        add("fs.ready")
        add("fs.mount")
        add("fs.readall", "path")
        add("fs.writeall", "path", "data")
        add(":read", "n")
        add(":write", "s")
        add(":seek", "offset", "[whence]")
        add(":tell")
        add(":size")
        add(":flush")
        add(":close")

        // Generated by the IDE
        add("ApplyAssets")

        // Lua base
        add("assert", "v", "[message]")
        add("collectgarbage", "[opt]", "[arg]")
        add("dofile", "[filename]")
        add("error", "message", "[level]")
        add("getmetatable", "object")
        add("ipairs", "t")
        add("loadfile", "[filename]")
        add("next", "table", "[index]")
        add("pairs", "t")
        add("pcall", "f", "...")
        add("print", "...")
        add("rawequal", "v1", "v2")
        add("rawget", "table", "index")
        add("rawlen", "v")
        add("rawset", "table", "index", "value")
        add("require", "name")
        add("select", "n", "...")
        add("setmetatable", "table", "metatable")
        add("tonumber", "v", "[base]")
        add("tostring", "v")
        add("type", "v")
        add("xpcall", "f", "msgh", "...")

        // coroutine
        add("coroutine.close", "co")
        add("coroutine.create", "f")
        add("coroutine.isyieldable", "[co]")
        add("coroutine.resume", "co", "...")
        add("coroutine.running")
        add("coroutine.status", "co")
        add("coroutine.wrap", "f")
        add("coroutine.yield", "...")

        // string
        add("string.byte", "s", "[i]", "[j]")
        add("string.char", "...")
        add("string.find", "s", "pattern", "[init]", "[plain]")
        add("string.format", "formatstring", "...")
        add("string.gmatch", "s", "pattern", "[init]")
        add("string.gsub", "s", "pattern", "repl", "[n]")
        add("string.len", "s")
        add("string.lower", "s")
        add("string.match", "s", "pattern", "[init]")
        add("string.rep", "s", "n", "[sep]")
        add("string.reverse", "s")
        add("string.sub", "s", "i", "[j]")
        add("string.upper", "s")

        // table
        add("table.concat", "list", "[sep]", "[i]", "[j]")
        add("table.insert", "list", "[pos]", "value")
        add("table.move", "a1", "f", "e", "t", "[a2]")
        add("table.pack", "...")
        add("table.remove", "list", "[pos]")
        add("table.sort", "list", "[comp]")
        add("table.unpack", "list", "[i]", "[j]")

        // math
        add("math.abs", "x")
        add("math.ceil", "x")
        add("math.floor", "x")
        add("math.fmod", "x", "y")
        add("math.max", "x", "...")
        add("math.min", "x", "...")
        add("math.random", "[m]", "[n]")
        add("math.randomseed", "[x]")
        add("math.sqrt", "x")

        // utf8
        add("utf8.char", "...")
        add("utf8.codepoint", "s", "[i]", "[j]")
        add("utf8.codes", "s")
        add("utf8.len", "s", "[i]", "[j]")
        add("utf8.offset", "s", "n", "[i]")

        return result
    }()
}

/// Finds the function call the caret sits inside, for parameter help.
public enum LuaSignatureHelp {
    public struct Context: Equatable, Sendable {
        public let signature: LuaSignature
        /// 0-based parameter to highlight, or nil when the call already
        /// has more arguments than the signature declares.
        public let activeParameter: Int?

        public init(signature: LuaSignature, activeParameter: Int?) {
            self.signature = signature
            self.activeParameter = activeParameter
        }
    }

    /// The call context at `caret` (a UTF-16 offset into `text`), or nil
    /// when the caret is not inside a known function call's argument
    /// list. Strings and comments are ignored.
    public static func context(at caret: Int, in text: String) -> Context? {
        let ns = text as NSString
        guard caret >= 0, caret <= ns.length else { return nil }
        let masked = maskedText(text)
        guard let open = openParenthesis(before: caret, in: masked),
              let name = functionName(before: open, in: masked),
              let signature = LuaSignatures.signature(for: name)
        else { return nil }
        let arguments = argumentIndex(from: open + 1, to: caret, in: masked)
        return Context(
            signature: signature,
            activeParameter: signature.parameterIndex(forArgument: arguments))
    }

    /// Replaces strings and comments with spaces (same length, so offsets
    /// and newlines are preserved), which makes the backwards scan safe.
    static func maskedText(_ text: String) -> NSString {
        let ns = text as NSString
        var characters = [unichar](repeating: 0, count: ns.length)
        ns.getCharacters(&characters)
        for token in LuaTokenizer.tokenize(text)
        where token.kind == .string || token.kind == .comment {
            let start = max(0, token.range.location)
            let end = min(characters.count, start + token.range.length)
            for index in start..<end {
                characters[index] = 0x20
            }
        }
        return NSString(characters: characters, length: characters.count)
    }

    /// Nearest unmatched `(` before the caret, crossing newlines (calls
    /// may span lines).
    static func openParenthesis(before caret: Int, in text: NSString) -> Int? {
        var depth = 0
        var index = min(caret, text.length)
        while index > 0 {
            index -= 1
            switch text.character(at: index) {
            case 0x29, 0x5D, 0x7D: // ) ] }
                depth += 1
            case 0x28: // (
                if depth == 0 { return index }
                depth -= 1
            case 0x5B, 0x7B: // [ {
                if depth > 0 { depth -= 1 }
            default:
                break
            }
        }
        return nil
    }

    /// Identifier (`a.b`, `a:b`) immediately before the open parenthesis.
    static func functionName(before open: Int, in text: NSString) -> String? {
        func isName(_ c: unichar) -> Bool {
            (c >= 0x41 && c <= 0x5A) || (c >= 0x61 && c <= 0x7A)
                || (c >= 0x30 && c <= 0x39) || c == 0x5F || c == 0x2E || c == 0x3A
        }
        var end = open
        while end > 0, isSpace(text.character(at: end - 1)) {
            end -= 1
        }
        var start = end
        while start > 0, isName(text.character(at: start - 1)) {
            start -= 1
        }
        guard start < end else { return nil }
        let name = text.substring(with: NSRange(location: start, length: end - start))
        // File methods have any receiver: `f:read` -> ":read".
        if let colon = name.lastIndex(of: ":") {
            return String(name[colon...])
        }
        return name
    }

    /// Number of top-level commas between the open paren and the caret
    /// (that is, the 0-based argument the caret is in). Commas inside
    /// nested calls or table constructors do not count.
    static func argumentIndex(from start: Int, to caret: Int, in text: NSString) -> Int {
        var depth = 0
        var commas = 0
        var index = start
        while index < caret, index < text.length {
            switch text.character(at: index) {
            case 0x28, 0x5B, 0x7B: // ( [ {
                depth += 1
            case 0x29, 0x5D, 0x7D: // ) ] }
                if depth > 0 { depth -= 1 }
            case 0x2C: // ,
                if depth == 0 { commas += 1 }
            default:
                break
            }
            index += 1
        }
        return commas
    }

    private static func isSpace(_ c: unichar) -> Bool {
        c == 0x20 || c == 0x09 || c == 0x0A || c == 0x0D
    }
}
