-- ================================================================
-- boot
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-14T19:44:57Z from components:
--   snippet header
--   lua     main
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = true


-- ==== component: header (snippet) ====

-- boot.lua — the first program the OS runs.
--
-- Shows a static startup screen for two seconds, then hands the machine
-- over to the shell with Launch(..., replace): boot leaves the program
-- stack and its Lua state is released, so only the shell stays resident.
-- If neither compiled nor source OS image can be loaded, the failure is
-- displayed on screen and this program remains running.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/boot` from the workspace root. The generated files are written
-- to software/core/.

-- ==== component: main (lua) ====

local function text(row, message, attr)
    local x = math.max(0, math.floor((40 - #message) / 2))
    for i = 1, #message do
        ScreenOut(x + i - 1, row, message:byte(i), attr or 0)
    end
end

local function draw_boot()
    ScreenClear(32)
    text(8, "SPI COMPUTER", 0)
    text(10, "STARTING SYSTEM", 0)
    text(12, "PLEASE WAIT", 0)
    for x = 8, 31 do
        ScreenOut(x, 14, 32, 0x02)
    end
    for x = 8, 31 do
        ScreenOut(x, 14, 32, 0x00)
    end
end

local function draw_failure()
    ScreenClear(32)
    text(7, "SPI COMPUTER", 0)
    text(10, "SYSTEM STARTUP FAILED", 0x80)
    text(13, "CANNOT FIND OS IMAGE", 0x80)
    text(16, "EXPECTED CORE/OS.PRG", 0)
    text(17, "OR CORE/OS.LUA", 0)
    text(20, "CHECK THE SD CARD", 0)
end

-- Try each OS image once after the static startup screen has been shown.
-- Launch(..., true) replaces this program on success. A failure leaves
-- this program running with the error message on screen.
local function start_os()
    local ok = Launch("core/os.prg", nil, true)
    if not ok then
        ok = Launch("core/os.lua", nil, true)
    end
    if not ok then
        draw_failure()
    end
end

function setup()
    ScreenMode(1)
    ScreenPalette(0, 0, 0, 160)
    ScreenPalette(1, 255, 255, 255)
    ScreenPalette(2, 180, 220, 255)
    draw_boot()
    TimerCreate(start_os, 2000, true)
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
