-- ================================================================
-- os
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-14T22:56:23Z from components:
--   snippet header
--   lua     screen
--   lua     line-editor
--   lua     commands
--   lua     apps
--   lua     main
--   lua     tick
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = true


-- ==== component: header (snippet) ====

-- os.lua — the SPIOS shell (the command line).
--
-- Started by boot.lua at power-on. It owns the screen, echoes what you
-- type and runs programs in the foreground: the shell pauses (and its
-- screen state is saved by the OS) until the program exits.
--
-- Commands (HELP lists them too):
--   HELP                 this list
--   DIR                  list files in data
--   APPS                 pick an installed application from a list
--   RUN <prog> [args]    run a program from apps or data
--   <prog> [args]        run a program by name
--   COMPILE <file.lua>   build a .prg next to a data program
--
-- Everything else on the card is just a program: `editor notes.txt` or
-- `run editor notes.txt` both start the editor. There is no QUIT: the
-- shell is the OS, so it stays running once booted.
--
-- Arguments after a program name arrive in the program as the global
-- `args` table (args[1], args[2], ...). Typing a bare name such as
-- EDITOR finds an installed app or data program whatever its case.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/os` from the workspace root. The generated os.lua is written
-- to the parent folder (the SD card the OS boots from).

local COLS, ROWS = 40, 30
local KEY_RETURN = 13
local KEY_BACKSPACE = 8
local KEY_DELETE = 127
local KEY_LEFT = 130
local KEY_RIGHT = 131
local KEY_HOME = 139

-- ==== component: screen (lua) ====

-- Screen buffer: the shell keeps every output line and repaints the
-- tile map, so scrolling, resuming after a program and the blinking
-- cursor are all just a repaint of `lines` + `input`.

local lines = {}          -- committed output lines (one screen row each)
local input = ""          -- the line being typed
local caret_col = 0       -- 0-based caret position within `input`
local prompt_row = 0      -- screen row the input line sits on
local cursor_on = true
local last_blink = 0
local needs_repaint = false -- a program ran; redraw on the next tick
local dialog_open = false   -- the APPS picker owns the overlay and the keys

local function cursor_cell()
    local ch = 32
    if caret_col < #input then
        ch = input:byte(caret_col + 1)
    end
    return ch
end

local function paint_cursor()
    OverlayClear(32)
    if not cursor_on or prompt_row >= ROWS then
        return
    end
    local cx = math.min(caret_col, COLS - 1)
    OverlayOut(cx, prompt_row, cursor_cell(), 0x80)
end

local function paint()
    ScreenClear(32)
    OverlayClear(32)
    for i = 1, math.min(#lines, ROWS) do
        local line = lines[i]
        for c = 1, math.min(#line, COLS) do
            ScreenOut(c - 1, i - 1, line:byte(c))
        end
    end
    prompt_row = #lines
    for c = 1, math.min(#input, COLS) do
        if prompt_row < ROWS then
            ScreenOut(c - 1, prompt_row, input:byte(c))
        end
    end
    paint_cursor()
end

local function commit(line)
    lines[#lines + 1] = line
    if #lines > ROWS - 1 then
        table.remove(lines, 1)
    end
end

-- Write a message; "\n" separates lines.
local function out(message)
    for part in (tostring(message) .. "\n"):gmatch("([^\n]*)\n") do
        commit(part)
    end
    paint()
end

-- ==== component: line-editor (lua) ====

-- Line editor: the input line is a plain string with a caret index;
-- every key changes it and the shell repaints.

local function insert_char(ch)
    if #input >= COLS - 1 then
        return
    end
    input = input:sub(1, caret_col) .. ch .. input:sub(caret_col + 1)
    caret_col = caret_col + 1
end

local function backspace()
    if caret_col == 0 then
        return
    end
    input = input:sub(1, caret_col - 1) .. input:sub(caret_col + 1)
    caret_col = caret_col - 1
end

local function keyboard(event)
    local key = event.key
    if key == KEY_BACKSPACE then
        backspace()
    elseif key == KEY_DELETE then
        if caret_col < #input then
            input = input:sub(1, caret_col) .. input:sub(caret_col + 2)
        end
    elseif key == KEY_LEFT then
        caret_col = math.max(caret_col - 1, 0)
    elseif key == KEY_RIGHT then
        caret_col = math.min(caret_col + 1, #input)
    elseif key == KEY_HOME then
        caret_col = 0
    elseif key >= 32 and key < 127 then
        insert_char(string.char(key))
    end
end

-- ==== component: commands (lua) ====

-- Commands: built-ins plus program lookup on the card. Anything that
-- is not a built-in is looked up case-insensitively as <name>.prg or
-- <name>.lua and run in the foreground with the remaining words as its
-- `args`.

local cwd = "/"

local function tail(words, first)
    local args = {}
    for i = first, #words do
        args[#args + 1] = words[i]
    end
    return args
end

local function split_words(text)
    local words = {}
    for word in text:gmatch("%S+") do
        words[#words + 1] = word
    end
    return words
end

local function normalize(path)
    local parts = {}
    for part in path:gmatch("[^/]+") do
        if part == ".." then
            if #parts > 0 then
                table.remove(parts)
            end
        elseif part ~= "." then
            parts[#parts + 1] = part
        end
    end
    if #parts == 0 then
        return "/"
    end
    return "/" .. table.concat(parts, "/")
end

local function full_path(path)
    local logical = cwd
    if path and path ~= "" then
        logical = path:sub(1, 1) == "/" and normalize(path)
            or normalize(cwd .. "/" .. path)
    end
    return logical == "/" and "/data" or "/data" .. logical
end

local function parent_path(path)
    local slash = path:match("^.*()/")
    if not slash or slash == 1 then
        return "/"
    end
    return path:sub(1, slash - 1)
end

local function display_path(path)
    if path == "/" then
        return "/"
    end
    return path:sub(2)
end

local function find_app_program(root, entry)
    local folder = root .. "/" .. entry
    local info = fs.stat(folder)
    if not info or not info.dir then
        return nil
    end
    local compiled = fs.find("app.prg", folder)
    if compiled then return folder .. "/" .. compiled end
    local source = fs.find("app.lua", folder)
    if source then return folder .. "/" .. source end
    return nil
end

local function find_program(name)
    local roots = { "/apps", "/data" }
    local lower = name:lower()
    local names = { name }
    if not lower:match("%.lua$") and not lower:match("%.prg$") then
        names = { name .. ".prg", name .. ".lua", name .. ".app" }
    end
    for _, root in ipairs(roots) do
        for _, candidate in ipairs(names) do
            local found = fs.find(candidate, root)
            if found then
                local app = find_app_program(root, found)
                if app then return app end
                local info = fs.stat(root .. "/" .. found)
                if info and not info.dir then return root .. "/" .. found end
            end
        end
    end
    return nil
end

local function run_program(path, args)
    if args[1] and args[1]:sub(1, 1) ~= "/" then
        args[1] = full_path(args[1])
    end
    local ok, err = Execute(path, table.unpack(args))
    if not ok then
        out("?" .. tostring(err))
        return
    end
    needs_repaint = true
end

local function command_error(err)
    out("?" .. tostring(err))
end

local function cmd_help()
    out("COMMANDS:")
    out("  HELP              THIS LIST")
    out("  DIR [PATH]        LIST DATA FILES")
    out("  APPS              CHOOSE AN APP TO RUN")
    out("  CD [PATH]         CHANGE DATA DIRECTORY")
    out("  PWD               SHOW DATA DIRECTORY")
    out("  MD <DIR>          CREATE A DIRECTORY")
    out("  RD <DIR>          REMOVE AN EMPTY DIRECTORY")
    out("  DEL <FILE>        DELETE A FILE")
    out("  REN <OLD> <NEW>   RENAME OR MOVE")
    out("  COPY <FROM> <TO>  COPY A FILE")
    out("  TYPE <FILE>       DISPLAY A TEXT FILE")
    out("  STAT <PATH>       SHOW FILE INFORMATION")
    out("  COMPILE <FILE>    BUILD A .PRG FROM A .LUA")
    out("  FREE              SHOW CARD SPACE")
    out("  MOUNT             REMOUNT THE CARD")
    out("  CLS               CLEAR THE SCREEN")
    out("  MODE [0|1]        CHANGE TEXT MODE")
    out("  ECHO <TEXT>       PRINT TEXT")
    out("  TIME              SHOW MILLISECONDS")
    out("  RUN <PROG> [ARGS] RUN A PROGRAM")
    out("  <PROG> [ARGS]     RUN A PROGRAM BY NAME")
end

local function cmd_dir(path)
    local target = full_path(path)
    local entries, err = fs.ls(target)
    if not entries then
        command_error(err)
        return
    end
    out("DIRECTORY OF DATA/" .. (path or "") .. ":")
    for _, entry in ipairs(entries) do
        out(string.format("  %-22s %7d %s", entry.name, entry.size,
                          entry.dir and "<DIR>" or "     "))
    end
end

-- APPS opens the picker dialog (assigned in 35-apps.lua, which follows
-- this component); the shell's prompt waits until it closes or an app
-- is launched.
local open_apps_dialog

local function cmd_apps()
    open_apps_dialog()
end

local function cmd_cd(path)
    local target = full_path(path)
    local info, err = fs.stat(target)
    if not info then
        command_error(err)
        return
    end
    if not info.dir then
        out("?NOT A DIRECTORY")
        return
    end
    cwd = target
end

local function cmd_mkdir(path)
    if not path then
        out("USAGE: MD <DIRECTORY>")
        return
    end
    local ok, err = fs.mkdir(full_path(path))
    if not ok then command_error(err) end
end

local function cmd_remove(path, directory)
    if not path then
        out(directory and "USAGE: RD <DIRECTORY>" or "USAGE: DEL <FILE>")
        return
    end
    local target = full_path(path)
    local info, err = fs.stat(target)
    if not info then
        command_error(err)
        return
    end
    if directory ~= info.dir then
        out(directory and "?NOT A DIRECTORY" or "?IS A DIRECTORY")
        return
    end
    local ok, remove_error = fs.remove(target)
    if not ok then command_error(remove_error) end
end

local function cmd_rename(old_path, new_path)
    if not old_path or not new_path then
        out("USAGE: REN <OLD> <NEW>")
        return
    end
    local ok, err = fs.rename(full_path(old_path), full_path(new_path))
    if not ok then command_error(err) end
end

local function cmd_copy(source, destination)
    if not source or not destination then
        out("USAGE: COPY <FROM> <TO>")
        return
    end
    local data, err = fs.readall(full_path(source))
    if not data then
        command_error(err)
        return
    end
    local ok, write_error = fs.writeall(full_path(destination), data)
    if not ok then command_error(write_error) end
end

local function cmd_type(path)
    if not path then
        out("USAGE: TYPE <FILE>")
        return
    end
    local data, err = fs.readall(full_path(path))
    if not data then
        command_error(err)
        return
    end
    out(data:gsub("\n$", ""))
end

local function cmd_stat(path)
    if not path then
        out("USAGE: STAT <PATH>")
        return
    end
    local target = full_path(path)
    local info, err = fs.stat(target)
    if not info then
        command_error(err)
        return
    end
    out(string.format("PATH: %s", target))
    out(string.format("TYPE: %s", info.dir and "DIRECTORY" or "FILE"))
    out(string.format("SIZE: %d BYTES", info.size))
end

local function cmd_free()
    local free, total = fs.free()
    if not free then
        out("?CARD SPACE UNAVAILABLE")
        return
    end
    out(string.format("CARD SPACE: %d KB FREE / %d KB TOTAL", free, total))
end

local function cmd_mode(value)
    if not value then
        out(string.format("TEXT MODE: %d (%dx%d)", shell_mode, COLS, ROWS))
        return
    end
    local mode = tonumber(value)
    if mode ~= 0 and mode ~= 1 then
        out("?USE MODE 0 OR 1")
        return
    end
    local ok, err = ScreenMode(mode)
    if not ok then
        command_error(err)
        return
    end
    shell_mode = mode
    if mode == 0 or mode == 1 then
        COLS, ROWS = 40, 30
    else
        COLS, ROWS = 80, 60
    end
    lines = {}
    input = ""
    caret_col = 0
    prompt_row = 0
    paint()
end

-- COMPILE <FILE.LUA> [OUT]: build a .prg next to the source (or at OUT)
-- with the OS's own compiler, so a program written on the card with the
-- editor loads as fast as one built by the IDE. The OS prefers a .prg
-- over its .lua sibling when a program is run by name.
local function cmd_compile(source, destination)
    if not source then
        out("USAGE: COMPILE <FILE.LUA> [OUT.PRG]")
        return
    end
    local src = full_path(source)
    local dst = destination and full_path(destination) or nil
    local ok, result = Compile(src, dst)
    if not ok then
        command_error(result)
        return
    end
    local shown = dst or (src:gsub("%.[Ll][Uu][Aa]$", "") .. ".prg")
    shown = shown:gsub("^/data", "")
    if shown == "" then shown = "/" end
    out(string.format("%s: %d BYTES", display_path(shown), result))
end

local function execute(command_line)
    local words = split_words(command_line)
    local name = words[1]
    if not name then
        return
    end
    local lower = name:lower()
    if lower == "help" or lower == "?" then
        cmd_help()
    elseif lower == "apps" then
        cmd_apps()
    elseif lower == "dir" or lower == "ls" or lower == "catalog" then
        cmd_dir(words[2])
    elseif lower == "cd" or lower == "chdir" then
        cmd_cd(words[2])
    elseif lower == "pwd" then
        out(cwd)
    elseif lower == "md" or lower == "mkdir" then
        cmd_mkdir(words[2])
    elseif lower == "rd" or lower == "rmdir" then
        cmd_remove(words[2], true)
    elseif lower == "del" or lower == "erase" or lower == "rm" then
        cmd_remove(words[2], false)
    elseif lower == "ren" or lower == "rename" or lower == "move" then
        cmd_rename(words[2], words[3])
    elseif lower == "copy" or lower == "cp" then
        cmd_copy(words[2], words[3])
    elseif lower == "type" or lower == "cat" or lower == "print" then
        cmd_type(words[2])
    elseif lower == "stat" or lower == "info" then
        cmd_stat(words[2])
    elseif lower == "free" then
        cmd_free()
    elseif lower == "compile" then
        cmd_compile(words[2], words[3])
    elseif lower == "mount" then
        if not fs.mount() then out("?MOUNT FAILED") end
    elseif lower == "cls" or lower == "clear" then
        lines = {}
        paint()
    elseif lower == "mode" or lower == "resolution" then
        cmd_mode(words[2])
    elseif lower == "echo" then
        out(command_line:sub(#name + 2))
    elseif lower == "time" then
        out(string.format("%d MS", TimeNow()))
    elseif lower == "run" then
        local program = words[2]
        if not program then
            out("USAGE: RUN <PROGRAM> [ARGS]")
            return
        end
        local path = find_program(program)
        if not path then
            out("?FILE NOT FOUND: " .. program)
            return
        end
        run_program(path, tail(words, 3))
    else
        local path = find_program(name)
        if not path then
            out("?FILE NOT FOUND: " .. name)
            return
        end
        run_program(path, tail(words, 2))
    end
end

local function submit()
    local command_line = input
    commit(command_line)
    input = ""
    caret_col = 0
    paint()
    execute(command_line)
    if not needs_repaint and not dialog_open then
        out("READY.")
    end
end

-- ==== component: apps (lua) ====

-- APPS picker: a dialog on the overlay listing the installed apps by
-- name and description (from each bundle's app.json), scrolled with the
-- cursor keys. RETURN runs the selected app, ESC or RUN/STOP closes.
-- While it is open the shell's prompt, cursor blink and line editor
-- are paused (see tick).

local KEY_UP = 128
local KEY_DOWN = 129
local KEY_ESCAPE = 27
local KEY_RUNSTOP = 140

local CH_POINTER = 16    -- right-pointing pointer
local CH_UP = 30         -- up-pointing triangle
local CH_DOWN = 31       -- down-pointing triangle
local CH_ARROW_UP = 24
local CH_ARROW_DOWN = 25

-- Dialog geometry: a double frame just inside the screen, two rows per
-- app (name and version, then the description).
local DLG_X, DLG_Y, DLG_W, DLG_H = 1, 2, 38, 26
local LIST_TOP = DLG_Y + 2
local LIST_ROWS = DLG_H - 4
local PAGE = LIST_ROWS // 2
local BODY = 0x80        -- inverted: the dialog body
local HILITE = 0x00      -- plain: the selected app reads as a bar

local apps = {}          -- { name, version, description, path }
local selected = 1
local scroll = 0         -- index of the first visible app minus one

-- Minimal JSON reader for app.json (objects, arrays, strings, numbers,
-- true/false/null). Returns nil on malformed input.
local function json_decode(text)
    local pos = 1
    local value

    local function skip()
        pos = text:find("[^ \t\r\n]", pos) or #text + 1
    end

    local function str()
        local out = {}
        pos = pos + 1
        while pos <= #text do
            local c = text:sub(pos, pos)
            if c == '"' then
                pos = pos + 1
                return table.concat(out)
            elseif c == "\\" then
                local e = text:sub(pos + 1, pos + 1)
                local map = { n = "\n", t = "\t", r = "\r", b = "\b", f = "\f" }
                if e == "u" then
                    local code = tonumber(text:sub(pos + 2, pos + 5), 16) or 63
                    out[#out + 1] = code < 128 and string.char(code) or "?"
                    pos = pos + 6
                else
                    out[#out + 1] = map[e] or e
                    pos = pos + 2
                end
            else
                out[#out + 1] = c
                pos = pos + 1
            end
        end
        return nil
    end

    value = function()
        skip()
        local c = text:sub(pos, pos)
        if c == "{" then
            local obj = {}
            pos = pos + 1
            skip()
            if text:sub(pos, pos) == "}" then pos = pos + 1 return obj end
            while true do
                skip()
                if text:sub(pos, pos) ~= '"' then return nil end
                local key = str()
                if not key then return nil end
                skip()
                if text:sub(pos, pos) ~= ":" then return nil end
                pos = pos + 1
                local v = value()
                if v == nil and text:sub(pos - 4, pos - 1) ~= "null" then return nil end
                obj[key] = v
                skip()
                local sep = text:sub(pos, pos)
                pos = pos + 1
                if sep == "}" then return obj end
                if sep ~= "," then return nil end
            end
        elseif c == "[" then
            local arr = {}
            pos = pos + 1
            skip()
            if text:sub(pos, pos) == "]" then pos = pos + 1 return arr end
            while true do
                local v = value()
                arr[#arr + 1] = v
                skip()
                local sep = text:sub(pos, pos)
                pos = pos + 1
                if sep == "]" then return arr end
                if sep ~= "," then return nil end
            end
        elseif c == '"' then
            return str()
        elseif text:sub(pos, pos + 3) == "true" then
            pos = pos + 4
            return true
        elseif text:sub(pos, pos + 4) == "false" then
            pos = pos + 5
            return false
        elseif text:sub(pos, pos + 3) == "null" then
            pos = pos + 4
            return nil
        else
            local num = text:match("^-?%d+%.?%d*[eE]?[-+]?%d*", pos)
            if not num or num == "" then return nil end
            pos = pos + #num
            return tonumber(num)
        end
    end

    local ok, result = pcall(value)
    if ok then return result end
    return nil
end

-- Scan /apps: bundles (folders with app.json) carry their metadata,
-- loose .prg/.lua programs are listed by file name.
local function load_apps()
    local found = {}
    local entries = fs.ls("/apps")
    if not entries then
        return found
    end
    for _, entry in ipairs(entries) do
        local lower = entry.name:lower()
        if entry.dir then
            local program = find_app_program("/apps", entry.name)
            if program then
                local meta = {}
                local text = fs.readall("/apps/" .. entry.name .. "/app.json")
                if text then
                    meta = json_decode(text) or {}
                end
                found[#found + 1] = {
                    name = tostring(meta.name or entry.name:gsub("%.app$", "")),
                    version = meta.version and tostring(meta.version) or "",
                    description = tostring(meta.description or ""),
                    path = program,
                }
            end
        elseif lower:match("%.prg$") or lower:match("%.lua$") then
            found[#found + 1] = {
                name = entry.name:gsub("%.[^.]+$", ""),
                version = "",
                description = "",
                path = "/apps/" .. entry.name,
            }
        end
    end
    table.sort(found, function(a, b) return a.name:lower() < b.name:lower() end)
    return found
end

local function dialog_text(x, y, s, attr)
    for i = 1, math.min(#s, DLG_X + DLG_W - 1 - x) do
        OverlayOut(x + i - 1, y, s:byte(i), attr)
    end
end

local function draw_dialog()
    OverlayClear(32)
    OverlayFill(DLG_X, DLG_Y, DLG_W, DLG_H, 32, BODY)
    OverlayBox(DLG_X, DLG_Y, DLG_W, DLG_H, 2, BODY)
    dialog_text(DLG_X + (DLG_W - 6) // 2, DLG_Y, " APPS ", BODY)

    if #apps == 0 then
        dialog_text(DLG_X + 10, LIST_TOP + 4, "NO APPS INSTALLED", BODY)
    end
    local inner_x = DLG_X + 1
    local inner_w = DLG_W - 2
    for i = 1, PAGE do
        local app = apps[scroll + i]
        if not app then break end
        local row = LIST_TOP + (i - 1) * 2
        local attr = (scroll + i == selected) and HILITE or BODY
        OverlayFill(inner_x, row, inner_w, 2, 32, attr)
        if attr == HILITE then
            OverlayOut(inner_x, row, CH_POINTER, attr)
        end
        local name = app.name:upper():sub(1, inner_w - 10)
        dialog_text(inner_x + 2, row, name, attr)
        if app.version ~= "" then
            local ver = ("V" .. app.version):sub(1, 7)
            dialog_text(inner_x + inner_w - #ver, row, ver, attr)
        end
        dialog_text(inner_x + 2, row + 1, app.description:sub(1, inner_w - 3), attr)
    end

    -- Scroll indicators on the frame's right edge.
    local edge = DLG_X + DLG_W - 1
    if scroll > 0 then
        OverlayOut(edge, LIST_TOP, CH_UP, BODY)
    end
    if scroll + PAGE < #apps then
        OverlayOut(edge, LIST_TOP + LIST_ROWS - 1, CH_DOWN, BODY)
    end

    local footer = string.char(CH_ARROW_UP, CH_ARROW_DOWN) ..
        " SELECT  RETURN RUN  ESC CLOSE"
    dialog_text(DLG_X + (DLG_W - #footer) // 2, DLG_Y + DLG_H - 1, footer, BODY)
end

open_apps_dialog = function()
    apps = load_apps()
    selected = 1
    scroll = 0
    dialog_open = true
    draw_dialog()
end

local function close_apps_dialog()
    dialog_open = false
    OverlayClear(32)
    paint()
end

local function dialog_key(key)
    if key == KEY_ESCAPE or key == KEY_RUNSTOP or key == 113 or key == 81 then
        close_apps_dialog()
        out("READY.")
    elseif key == KEY_UP then
        if selected > 1 then selected = selected - 1 end
    elseif key == KEY_DOWN then
        if selected < #apps then selected = selected + 1 end
    elseif key == KEY_HOME then
        selected = 1
    elseif key == KEY_RETURN then
        local app = apps[selected]
        close_apps_dialog()
        if app then
            run_program(app.path, {})
        else
            out("READY.")
        end
        return
    else
        return
    end
    if dialog_open then
        if selected <= scroll then
            scroll = selected - 1
        elseif selected > scroll + PAGE then
            scroll = selected - PAGE
        end
        draw_dialog()
    end
end

-- ==== component: main (lua) ====

-- Startup: C64-style colours, banner and the first READY. prompt.

local function banner()
    out("")
    out("     **** SPIComputer OS v1.0 ****")
    out("")
    local free_kb = 0
    local ok, free = pcall(fs.free)
    if ok and type(free) == "number" then
        free_kb = free
    end
    if free_kb >= 1024 then
        out(string.format(" %s   SD CARD %d MB FREE", _VERSION, free_kb // 1024))
    else
        out(string.format(" %s   SD CARD %d KB FREE", _VERSION, free_kb))
    end
    out("")
    out("READY.")
end

function setup()
    ScreenMode(1) -- 40x30 tiles, invert + colour
    ScreenPalette(0, 0x00, 0x00, 0xAA) -- background: CPC blue
    ScreenPalette(1, 0xFF, 0xFF, 0x00) -- default text: CPC yellow
    ScreenPalette(2, 0xFF, 0xFF, 0x00) -- attribute colour 1: CPC yellow
    banner()
end

-- ==== component: tick (lua) ====

-- Main loop: blink the cursor, run the input line, repaint after a
-- launched program returns.

function tick()
    local utility_ok, utility_message = UtilityPoll()
    if utility_ok ~= nil then
        out((utility_ok and "" or "?") .. utility_message)
        needs_repaint = true
    end
    if needs_repaint then
        needs_repaint = false
        paint()
        out("READY.")
    end

    -- The APPS picker takes every key while it is open; the prompt and
    -- its cursor blink wait (a blink would clear the overlay it lives on).
    if dialog_open then
        while true do
            local event = InputPoll()
            if not event then
                break
            end
            if event.type == "key" and event.pressed == 1 then
                dialog_key(event.key)
                if not dialog_open then
                    break
                end
            end
        end
        return
    end

    local now = TimeNow()
    if now - last_blink >= 500 then
        last_blink = now
        cursor_on = not cursor_on
        paint_cursor()
    end

    local changed = false
    while true do
        local event = InputPoll()
        if not event then
            break
        end
        if event.type == "key" and event.pressed == 1 then
            if event.key == KEY_RETURN then
                submit()
            else
                keyboard(event)
            end
            changed = true
        end
    end
    -- A command may have opened the APPS picker: leave its overlay alone.
    if changed and not dialog_open then
        cursor_on = true
        paint()
    end
end

function finish()
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
