import Foundation
import Testing

@testable import SPIIDECore

@Suite("Project builder")
struct BuilderTests {
    private func makeProject() throws -> Project {
        let parent = FileManager.default.temporaryDirectory
            .appendingPathComponent("spiide-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
        return try ProjectStore.createProject(named: "Demo", in: parent)
    }

    @Test func buildsTemplateInOrderWithAssetHelper() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let product = try ProjectBuilder.build(project, writeToDisk: false)
        let lua = product.lua

        #expect(lua.contains("Generated by the SPIComputer IDE"))
        #expect(lua.contains("component: header (snippet)"))
        #expect(lua.contains("component: main (lua)"))
        #expect(lua.contains("component: input (lua)"))
        #expect(lua.contains("component: tick (lua)"))
        let headerIndex = try #require(lua.range(of: "component: header"))
        let mainIndex = try #require(lua.range(of: "component: main"))
        let inputIndex = try #require(lua.range(of: "component: input"))
        let tickIndex = try #require(lua.range(of: "component: tick"))
        #expect(headerIndex.lowerBound < mainIndex.lowerBound)
        #expect(mainIndex.lowerBound < inputIndex.lowerBound)
        #expect(inputIndex.lowerBound < tickIndex.lowerBound)
        #expect(lua.contains("function ApplyAssets()"))
        #expect(lua.contains("__spi_assets"))
        #expect(product.componentCount == 4)
    }

    @Test func lineMapResolvesComponentLines() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let main = try #require(project.manifest.components.first { $0.name == "main" })
        try ProjectStore.writeText("-- one\n-- two\n-- three\n", to: project.fileURL(for: main))

        let product = try ProjectBuilder.build(project, writeToDisk: false)
        let lines = product.lua.split(separator: "\n", omittingEmptySubsequences: false)
        let generatedIndex = try #require(lines.firstIndex(of: "-- two"))
        let generatedLine = generatedIndex + 1

        let location = try #require(product.lineMap.source(forGeneratedLine: generatedLine))
        #expect(location.componentID == main.id)
        #expect(location.line == 2)

        // The banner and the asset helper are generated code (no mapping).
        #expect(product.lineMap.source(forGeneratedLine: 1) == nil)
        let helperIndex = try #require(lines.firstIndex(of: "function ApplyAssets()"))
        #expect(product.lineMap.source(forGeneratedLine: helperIndex + 1) == nil)
    }

    @Test func emitsTilesAsset() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let ref = ComponentRef(name: "sprites", kind: .tiles, file: "components/sprites.json")
        let asset = TilesAsset(
            palette: [RGB(r: 0, g: 0, b: 0), RGB(r: 255, g: 40, b: 1)],
            tiles: [TileDef(index: 128, rows: [0, 12, 30, 51, 51, 63, 51, 0])])
        try ProjectStore.writeTiles(asset, for: ref, in: project)
        project.manifest.components.append(ref)

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("local function __asset_sprites()"))
        #expect(lua.contains("ScreenPaletteSet({ { 0, 0, 0 }, { 255, 40, 1 } })"))
        #expect(lua.contains("ScreenDefineTile(128, { 0, 12, 30, 51, 51, 63, 51, 0 })"))
        #expect(lua.contains("table.insert(__spi_assets, __asset_sprites)"))
    }

    @Test func emitsAudioAsset() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let ref = ComponentRef(name: "theme", kind: .audio, file: "components/theme.json")
        var asset = AudioAsset()
        asset.sounds = [SoundDef(id: 3, wave: .pulse, duty: 4, attack: 1, decay: 2,
                                 sustain: 100, release: 30, volume: 200)]
        asset.scores = [ScoreDef(
            name: "intro",
            loop: true,
            channels: [[
                NoteEvent(at: 0, sound: 3, note: "C4", dur: 250, vol: 255, pan: -10),
                NoteEvent(at: 300, sound: 3, note: "72", dur: 250, vol: 255, pan: 0),
            ]])]
        try ProjectStore.writeAudio(asset, for: ref, in: project)
        project.manifest.components.append(ref)

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("local function __asset_theme()"))
        #expect(lua.contains("SoundDefine(3, {"))
        #expect(lua.contains("wave = \"pulse\""))
        #expect(lua.contains("duty = 4"))
        #expect(lua.contains("MusicDefine(\"intro\", {"))
        #expect(lua.contains("loop = true"))
        #expect(lua.contains("note = \"C4\""))
        #expect(lua.contains("note = 72"))
        #expect(lua.contains("pan = -10"))
    }

    @Test func missingComponentFileThrows() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.components.append(
            ComponentRef(name: "ghost", kind: .lua, file: "components/ghost.lua"))

        #expect(throws: BuildError.missingComponentFile("components/ghost.lua")) {
            _ = try ProjectBuilder.render(project)
        }
    }

    @Test func utilityProjectMarksGeneratedProgramNoninteractive() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.interactive = false

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("__spi_interactive = false"))
    }

    @Test func buildWritesOutputFile() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let product = try ProjectBuilder.build(project)
        #expect(FileManager.default.fileExists(atPath: product.outputURL.path))
        #expect(product.outputURL.lastPathComponent == "Demo.lua")
        let onDisk = try String(contentsOf: product.outputURL, encoding: .utf8)
        #expect(onDisk == product.lua)
    }

    @Test func runSessionUsesCompiledProductWhenAvailable() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        let product = try ProjectBuilder.build(project)
        let bytecode = Data([0x1b, 0x4c, 0x75, 0x61])
        try bytecode.write(to: project.prgProductURL)

        let session = try Runner.prepare(project: project, build: product)
        #expect(session.programURL.lastPathComponent == "Demo.prg")
        #expect(try Data(contentsOf: session.programURL) == bytecode)
        #expect(FileManager.default.fileExists(atPath: project.prgProductURL.path))
    }

    @Test func runSessionWritesSdCard() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        let product = try ProjectBuilder.build(project)

        let session = try Runner.prepare(project: project, build: product)
        let fm = FileManager.default
        #expect(fm.fileExists(atPath: session.programURL.path))
        let onCard = try String(contentsOf: session.programURL, encoding: .utf8)
        #expect(onCard == product.lua)
        #expect(Runner.simulatorArguments(for: session) == [
            "--sdcard", session.sdcardURL.path,
            "--boot", "Demo.lua",
        ])
    }

    @Test func runSessionKeepsProgramNamedOS() throws {
        // A project named "OS" used to be clobbered by the simulator's
        // boot file: on a case-insensitive filesystem the generated
        // os.lua launcher and OS.lua are the same file.
        let parent = FileManager.default.temporaryDirectory
            .appendingPathComponent("spiide-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: parent) }
        let project = try ProjectStore.createProject(named: "OS", in: parent)
        let product = try ProjectBuilder.build(project)

        let session = try Runner.prepare(project: project, build: product)
        #expect(session.programURL.lastPathComponent == "OS.lua")
        let onCard = try String(contentsOf: session.programURL, encoding: .utf8)
        #expect(onCard == product.lua)
        #expect(Runner.simulatorArguments(for: session) == [
            "--sdcard", session.sdcardURL.path,
            "--boot", "OS.lua",
        ])
    }
}
