import Foundation
import Testing

@testable import SPIIDECore

@Suite("Project builder")
struct BuilderTests {
    private func makeProject() throws -> Project {
        let parent = FileManager.default.temporaryDirectory
            .appendingPathComponent("spiide-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: parent, withIntermediateDirectories: true)
        return try ProjectStore.createProject(named: "Demo", in: parent)
    }

    @Test func buildsTemplateInOrderWithAssetHelper() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let product = try ProjectBuilder.build(project, writeToDisk: false)
        let lua = product.lua

        #expect(lua.contains("Generated by the SPIComputer IDE"))
        #expect(lua.contains("component: header (snippet)"))
        #expect(lua.contains("component: main (lua)"))
        #expect(lua.contains("component: input (lua)"))
        #expect(lua.contains("component: tick (lua)"))
        let headerIndex = try #require(lua.range(of: "component: header"))
        let mainIndex = try #require(lua.range(of: "component: main"))
        let inputIndex = try #require(lua.range(of: "component: input"))
        let tickIndex = try #require(lua.range(of: "component: tick"))
        #expect(headerIndex.lowerBound < mainIndex.lowerBound)
        #expect(mainIndex.lowerBound < inputIndex.lowerBound)
        #expect(inputIndex.lowerBound < tickIndex.lowerBound)
        #expect(lua.contains("function ApplyAssets()"))
        #expect(lua.contains("__spi_assets"))
        #expect(product.componentCount == 4)
    }

    @Test func injectsSelectedFrameworksStrippedToWhatIsUsed() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        let main = try #require(project.manifest.components.first { $0.name == "main" })
        try ProjectStore.writeText(
            "function setup()\n  Screen.CenterText(1, 'hi')\n  Overlay.Dialog('T', 'x')\nend\n",
            to: project.fileURL(for: main))
        project.manifest.sdks = ["screen", "overlay", "sound"]

        let lua = try ProjectBuilder.build(project, writeToDisk: false).lua
        #expect(lua.contains("-- ==== sdk: screen (read-only; unused functions stripped) ===="))
        #expect(lua.contains("function Screen.CenterText("))
        #expect(!lua.contains("function Screen.Box("), "unused Screen function stripped")
        #expect(lua.contains("function Overlay.Dialog("))
        #expect(lua.contains("function Overlay.Window("), "Dialog depends on Window")
        #expect(!lua.contains("function Overlay.Scroll("))
        #expect(lua.contains("sdk: sound (read-only; nothing used, nothing emitted)"))
        #expect(!lua.contains("function Sound.Tone("))
        // Frameworks precede the components and follow the flags.
        let flags = try #require(lua.range(of: "__spi_requires_audio"))
        let sdk = try #require(lua.range(of: "sdk: screen"))
        let component = try #require(lua.range(of: "component: header"))
        #expect(flags.lowerBound < sdk.lowerBound && sdk.lowerBound < component.lowerBound)
    }

    @Test func newProjectsSelectEveryFramework() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        #expect(project.manifest.sdks == SDKLibrary.available.map(\.id))
        let reloaded = try ProjectStore.load(from: project.root)
        #expect(reloaded.manifest.sdks == project.manifest.sdks)
    }

    @Test func unknownFrameworkFailsTheBuild() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.sdks = ["nosuch"]
        #expect(throws: BuildError.unknownSDK("nosuch")) {
            try ProjectBuilder.build(project, writeToDisk: false)
        }
    }

    @Test func lineMapResolvesComponentLines() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let main = try #require(project.manifest.components.first { $0.name == "main" })
        try ProjectStore.writeText("-- one\n-- two\n-- three\n", to: project.fileURL(for: main))

        let product = try ProjectBuilder.build(project, writeToDisk: false)
        let lines = product.lua.split(separator: "\n", omittingEmptySubsequences: false)
        let generatedIndex = try #require(lines.firstIndex(of: "-- two"))
        let generatedLine = generatedIndex + 1

        let location = try #require(product.lineMap.source(forGeneratedLine: generatedLine))
        #expect(location.componentID == main.id)
        #expect(location.line == 2)

        // The banner and the asset helper are generated code (no mapping).
        #expect(product.lineMap.source(forGeneratedLine: 1) == nil)
        let helperIndex = try #require(lines.firstIndex(of: "function ApplyAssets()"))
        #expect(product.lineMap.source(forGeneratedLine: helperIndex + 1) == nil)
    }

    @Test func emitsTilesAsset() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let ref = ComponentRef(name: "sprites", kind: .tiles, file: "components/sprites.json")
        let asset = TilesAsset(
            palette: [RGB(r: 0, g: 0, b: 0), RGB(r: 255, g: 40, b: 1)],
            tiles: [TileDef(index: 128, rows: [0, 12, 30, 51, 51, 63, 51, 0])])
        try ProjectStore.writeTiles(asset, for: ref, in: project)
        project.manifest.components.append(ref)

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("local function __asset_sprites()"))
        #expect(lua.contains("ScreenPaletteSet({ { 0, 0, 0 }, { 255, 40, 1 } })"))
        #expect(lua.contains("ScreenDefineTile(128, { 0, 12, 30, 51, 51, 63, 51, 0 })"))
        #expect(lua.contains("table.insert(__spi_assets, __asset_sprites)"))
    }

    @Test func emitsAudioAsset() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let ref = ComponentRef(name: "theme", kind: .audio, file: "components/theme.json")
        var asset = AudioAsset()
        asset.sounds = [SoundDef(id: 3, wave: .pulse, duty: 4, attack: 1, decay: 2,
                                 sustain: 100, release: 30, volume: 200)]
        asset.scores = [ScoreDef(
            name: "intro",
            loop: true,
            channels: [[
                NoteEvent(at: 0, sound: 3, note: "C4", dur: 250, vol: 255, pan: -10),
                NoteEvent(at: 300, sound: 3, note: "72", dur: 250, vol: 255, pan: 0),
            ]])]
        try ProjectStore.writeAudio(asset, for: ref, in: project)
        project.manifest.components.append(ref)

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("local function __asset_theme()"))
        #expect(lua.contains("SoundDefine(3, {"))
        #expect(lua.contains("wave = \"pulse\""))
        #expect(lua.contains("duty = 4"))
        #expect(lua.contains("MusicDefine(\"intro\", {"))
        #expect(lua.contains("loop = true"))
        #expect(lua.contains("note = \"C4\""))
        #expect(lua.contains("note = 72"))
        #expect(lua.contains("pan = -10"))
    }

    @Test func missingComponentFileThrows() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.components.append(
            ComponentRef(name: "ghost", kind: .lua, file: "components/ghost.lua"))

        #expect(throws: BuildError.missingComponentFile("components/ghost.lua")) {
            _ = try ProjectBuilder.render(project)
        }
    }

    @Test func utilityProjectMarksGeneratedProgramNoninteractive() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .utility

        let lua = try ProjectBuilder.render(project)
        #expect(lua.contains("__spi_interactive = false"))
    }

    @Test func productsLiveInTheProjectsBuildFolder() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        #expect(project.buildDirectoryURL == project.root.appendingPathComponent("build"))
        #expect(project.buildProductURL.lastPathComponent == "Demo.lua")
        #expect(project.prgProductURL.lastPathComponent == "Demo.prg")
        #expect(project.bundleName == "Demo.app")
        #expect(project.installDirectory == "apps")

        var game = project
        game.manifest.kind = .game
        #expect(game.bundleName == "Demo.game")
        #expect(game.installDirectory == "games")
        var raw = project
        raw.manifest.kind = .raw
        #expect(raw.bundleURL == nil)
        #expect(raw.installDirectory == "data")
        raw.manifest.installDirectory = "core"
        #expect(raw.installDirectory == "core")
    }

    @Test func bundleCarriesKindInMetadata() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .utility
        try ProjectBuilder.build(project)
        let fake = project.buildDirectoryURL.appendingPathComponent("fake.prg")
        try Data([0x1b, 0x4c, 0x75, 0x61]).write(to: fake)
        try ProjectBuilder.writeAppBundle(project, compiledURL: fake)

        let bundle = try #require(project.bundleURL)
        #expect(bundle.lastPathComponent == "Demo.util")
        let metadata = try JSONCoding.decode(
            AppMetadata.self, from: Data(contentsOf: bundle.appendingPathComponent("app.json")))
        #expect(metadata.type == "utility")
        #expect(!metadata.interactive)
        #expect(FileManager.default.fileExists(atPath: bundle.appendingPathComponent("app.prg").path))
    }

    @Test func buildWritesOutputFile() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }

        let product = try ProjectBuilder.build(project)
        #expect(FileManager.default.fileExists(atPath: product.outputURL.path))
        #expect(product.outputURL.lastPathComponent == "Demo.lua")
        let onDisk = try String(contentsOf: product.outputURL, encoding: .utf8)
        #expect(onDisk == product.lua)
    }

    private func fakeCompile(_ project: Project) throws {
        let bytecode = Data([0x1b, 0x4c, 0x75, 0x61])
        try FileManager.default.createDirectory(
            at: project.buildDirectoryURL, withIntermediateDirectories: true)
        try bytecode.write(to: project.prgProductURL)
        try ProjectBuilder.writeAppBundle(project, compiledURL: project.prgProductURL)
    }

    private func makeCardImage() throws -> URL {
        let card = FileManager.default.temporaryDirectory
            .appendingPathComponent("spiide-card-\(UUID().uuidString)")
        let core = card.appendingPathComponent("core")
        try FileManager.default.createDirectory(at: core, withIntermediateDirectories: true)
        try Data("-- boot".utf8).write(to: core.appendingPathComponent("boot.prg"))
        try Data("-- os".utf8).write(to: core.appendingPathComponent("os.prg"))
        return card
    }

    @Test func rawProgramRunsDirectlyFromTheRunCard() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .raw
        let product = try ProjectBuilder.build(project)
        try fakeCompile(project)

        let session = try Runner.prepare(project: project, build: product)
        #expect(!session.underOS)
        #expect(session.bootPath == "data/Demo.prg")
        #expect(Runner.simulatorArguments(for: session) == [
            "--sdcard", session.sdcardURL.path, "--boot", "data/Demo.prg",
        ])
        let onCard = session.sdcardURL.appendingPathComponent("data/Demo.prg")
        #expect(try Data(contentsOf: onCard) == Data([0x1b, 0x4c, 0x75, 0x61]))
        // The source goes along for reference; no OS is copied.
        #expect(FileManager.default.fileExists(atPath: session.sdcardURL.appendingPathComponent("data/Demo.lua").path))
        #expect(!FileManager.default.fileExists(atPath: session.sdcardURL.appendingPathComponent("core/boot.prg").path))
    }

    @Test func rawProgramWithoutCompilerBootsTheSource() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .raw
        let product = try ProjectBuilder.build(project)
        let session = try Runner.prepare(project: project, build: product)
        #expect(session.bootPath == "data/Demo.lua")
        let onCard = try String(contentsOf: session.sdcardURL.appendingPathComponent("data/Demo.lua"), encoding: .utf8)
        #expect(onCard == product.lua)
    }

    @Test func gameRunsDirectlyFromItsBundle() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .game
        let product = try ProjectBuilder.build(project)
        try fakeCompile(project)

        let session = try Runner.prepare(project: project, build: product)
        #expect(!session.underOS)
        #expect(session.bootPath == "games/Demo.game/app.prg")
        #expect(FileManager.default.fileExists(
            atPath: session.sdcardURL.appendingPathComponent("games/Demo.game/app.json").path))
    }

    @Test func applicationRunsUnderTheOSFromTheCardImage() throws {
        let project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        let product = try ProjectBuilder.build(project)
        try fakeCompile(project)
        let card = try makeCardImage()
        defer { try? FileManager.default.removeItem(at: card) }

        // Without a card image the OS cannot be provided.
        #expect(throws: RunError.noCardImage) {
            try Runner.prepare(project: project, build: product)
        }

        let session = try Runner.prepare(project: project, build: product, cardImage: card)
        #expect(session.underOS)
        #expect(session.bootPath == "core/boot.prg")
        let fm = FileManager.default
        #expect(fm.fileExists(atPath: session.sdcardURL.appendingPathComponent("core/os.prg").path))
        #expect(fm.fileExists(atPath: session.sdcardURL.appendingPathComponent("apps/Demo.app/app.prg").path))
        for folder in ["utils", "games", "data"] {
            #expect(fm.fileExists(atPath: session.sdcardURL.appendingPathComponent(folder).path))
        }

        // An image without an OS is refused with its path.
        let empty = fm.temporaryDirectory.appendingPathComponent("spiide-empty-\(UUID().uuidString)")
        try fm.createDirectory(at: empty, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: empty) }
        #expect(throws: RunError.cardImageHasNoOS(empty.path)) {
            try Runner.prepare(project: project, build: product, cardImage: empty)
        }
    }

    @Test func utilityInstallsIntoUtils() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        project.manifest.kind = .utility
        let product = try ProjectBuilder.build(project)
        try fakeCompile(project)
        let card = try makeCardImage()
        defer { try? FileManager.default.removeItem(at: card) }

        let session = try Runner.prepare(project: project, build: product, cardImage: card)
        #expect(session.underOS)
        #expect(FileManager.default.fileExists(
            atPath: session.sdcardURL.appendingPathComponent("utils/Demo.util/app.prg").path))
    }

    @Test func installCopiesProductsByKind() throws {
        var project = try makeProject()
        defer { try? FileManager.default.removeItem(at: project.root) }
        let card = FileManager.default.temporaryDirectory
            .appendingPathComponent("spiide-install-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: card) }
        let fm = FileManager.default

        // Not built yet: a clear error, nothing written.
        #expect(throws: ProjectInstaller.InstallError.notBuilt("Demo.app")) {
            try ProjectInstaller.install(project, into: card)
        }

        try ProjectBuilder.build(project)
        try fakeCompile(project)
        let app = try ProjectInstaller.install(project, into: card)
        #expect(app.map(\.lastPathComponent) == ["Demo.app"])
        #expect(fm.fileExists(atPath: card.appendingPathComponent("apps/Demo.app/app.json").path))
        for folder in ["core", "apps", "utils", "games", "data"] {
            #expect(fm.fileExists(atPath: card.appendingPathComponent(folder).path), "\(folder)/ exists")
        }

        // The shell: a raw program installed to core/.
        project.manifest.kind = .raw
        project.manifest.installDirectory = "core"
        try ProjectBuilder.build(project)
        try fakeCompile(project)
        let core = try ProjectInstaller.install(project, into: card)
        #expect(Set(core.map(\.lastPathComponent)) == ["Demo.prg", "Demo.lua"])
        #expect(fm.fileExists(atPath: card.appendingPathComponent("core/Demo.prg").path))

        // Reinstalling replaces the old bundle rather than merging into it.
        project.manifest.kind = .game
        project.manifest.installDirectory = nil
        try ProjectBuilder.build(project)
        try fakeCompile(project)
        try fm.createDirectory(at: card.appendingPathComponent("games/Demo.game/stale"), withIntermediateDirectories: true)
        try ProjectInstaller.install(project, into: card)
        #expect(!fm.fileExists(atPath: card.appendingPathComponent("games/Demo.game/stale").path))
        #expect(fm.fileExists(atPath: card.appendingPathComponent("games/Demo.game/app.prg").path))
    }
}
