-- ================================================================
-- apps
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-15T21:16:57Z from components:
--   snippet header
--   lua     main
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = false


-- ==== sdk: screen (read-only; unused functions stripped) ====

-- SDK: Screen
-- Summary: Text-mode drawing on the base layer: text, boxes, fills, block moves.
-- Namespaces: Screen, Attributes
--
-- A framework file the IDE injects, read-only, into programs that
-- select it. Its format is a contract with the builder:
--   * everything above the first top-level `function` is the preamble
--     and is always emitted;
--   * each `function Name.Sub(...)` ... `end` block (both at column 0)
--     is emitted only when the program refers to Name.Sub, directly or
--     from another emitted block;
--   * a top-level `local function helper(...)` ... `end` block is
--     emitted when an emitted block refers to `helper`;
--   * the `--- Name.Sub(x, y [, attr])` line above a block is its
--     signature for completion and parameter help; the `--` lines that
--     follow describe it.
--
-- Conventions: coordinates are 0-based cells; region calls take the two
-- inclusive corners (x1, y1, x2, y2), unlike the raw ScreenX calls,
-- which take (x, y, w, h). Every call returns what the OS call returns
-- (true, or nil and a message).

Screen = Screen or {}
Screen.COLS = 40       -- cells across in the current mode (Screen.Mode updates)
Screen.ROWS = 30       -- cells down in the current mode
Screen.TEXT40 = 0      -- mode: 40x30 tiles, B&W
Screen.TEXT40C = 1     -- mode: 40x30 tiles, colour
Screen.TEXT80 = 2      -- mode: 80x60 tiles, B&W
Screen.TEXT80C = 3     -- mode: 80x60 tiles, colour
Screen.PIXELS = 10     -- mode: 320x240 pixels
Screen.PIXELS_LO = 11  -- mode: 160x120 pixels
Screen.SINGLE = 1      -- box style: single line
Screen.DOUBLE = 2      -- box style: double line
Screen.INVERT = 0x80   -- attribute bit: swap foreground and background

-- Attribute values by name, for the `attr` argument of every drawing
-- call (Screen and Overlay): a colour, plus Attributes.Inverse to paint
-- the cell's background in that colour instead of its text. Add them:
-- `Attributes.Red + Attributes.Inverse` is a red block behind a space.
-- The colours are the mode-1 default palette (entries 1-8); a program
-- that changes the palette with Screen.Palette recolours them.
Attributes = Attributes or {}
Attributes.Normal = 0          -- white text on the background, not inverted
Attributes.White = 0
Attributes.Red = 1
Attributes.Cyan = 2
Attributes.Purple = 3
Attributes.Green = 4
Attributes.Blue = 5
Attributes.Yellow = 6
Attributes.Orange = 7
Attributes.Inverse = 0x80      -- swap text and background (a coloured block for a space)

-- Console-style output: OutLine writes at the cursor row and moves on,
-- scrolling the screen when it reaches the bottom.
local cursor_row = 0

-- Inclusive corners to (x, y, w, h), in either corner order.
local function region(x1, y1, x2, y2)
    if x2 < x1 then x1, x2 = x2, x1 end
    if y2 < y1 then y1, y2 = y2, y1 end
    return x1, y1, x2 - x1 + 1, y2 - y1 + 1
end

--- Screen.Mode(mode)
-- Selects a screen mode: 0 (40x30 B&W), 1 (40x30 colour), 2 (80x60
-- B&W), 3 (80x60 colour), 10 (320x240 pixels), 11 (160x120 pixels); the
-- Screen.TEXT40 .. Screen.PIXELS_LO constants name them. Switching
-- clears the screen and sets Screen.COLS/ROWS (and Overlay's, and
-- Graphics' WIDTH/HEIGHT) to the new geometry. The pixel modes have no
-- text cells: the Graphics framework draws there.
function Screen.Mode(mode)
    local ok, err = ScreenMode(mode)
    if ok then
        local wide = mode == 2 or mode == 3
        Screen.COLS = wide and 80 or 40
        Screen.ROWS = wide and 60 or 30
        if Overlay then
            Overlay.COLS, Overlay.ROWS = Screen.COLS, Screen.ROWS
        end
        if Graphics then
            Graphics.WIDTH = mode == 11 and 160 or 320
            Graphics.HEIGHT = mode == 11 and 120 or 240
        end
    end
    return ok, err
end

--- Screen.Clear([char])
-- Fills the whole base layer with `char` (default space) and attribute 0.
function Screen.Clear(char)
    return ScreenClear(char or 32)
end

--- Screen.Out(x, y, char [, attr])
-- Writes one character code at a cell.
function Screen.Out(x, y, char, attr)
    return ScreenOut(x, y, char, attr or 0)
end

--- Screen.OutText(x, y, text [, attr])
-- Writes a string from (x, y), wrapping at the right edge. One display
-- op however long the text.
function Screen.OutText(x, y, text, attr)
    return ScreenWrite(x, y, tostring(text), attr)
end

--- Screen.CenterText(y, text [, attr])
-- Writes a string centred on row `y`.
function Screen.CenterText(y, text, attr)
    text = tostring(text)
    local x = (Screen.COLS - #text) // 2
    if x < 0 then x = 0 end
    return ScreenWrite(x, y, text, attr)
end

--- Screen.Clean(x1, y1, x2, y2 [, char [, attr]])
-- Blanks the cells between two corners (inclusive): `char` defaults to
-- space and `attr` to 0.
function Screen.Clean(x1, y1, x2, y2, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenFill(x, y, w, h, char or 32, attr or 0)
end

--- Screen.Window(x1, y1, x2, y2 [, title [, style [, attr]]])
-- A blank window: the inside cleared, a frame around it and an optional
-- title on the top edge.
function Screen.Window(x1, y1, x2, y2, title, style, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    attr = attr or 0
    ScreenFill(x, y, w, h, 32, attr)
    local ok, err = ScreenBox(x, y, w, h, style or 1, attr)
    if ok and title and #tostring(title) > 0 then
        local label = " " .. tostring(title) .. " "
        local tx = x + (w - #label) // 2
        if tx < x + 1 then tx = x + 1 end
        ScreenWrite(tx, y, label:sub(1, w - 2), attr)
    end
    return ok, err
end

--- Screen.Label(x, y, width, text, align [, attr])
-- Writes `text` inside a `width`-cell field, padded and aligned "left",
-- "center" or "right" (default left); longer text is cut to the field.
function Screen.Label(x, y, width, text, align, attr)
    text = tostring(text)
    if #text > width then text = text:sub(1, width) end
    local space = width - #text
    local before = 0
    if align == "center" then before = space // 2
    elseif align == "right" then before = space end
    local padded = string.rep(" ", before) .. text .. string.rep(" ", space - before)
    return ScreenWrite(x, y, padded, attr)
end

-- ==== sdk: text (read-only; unused functions stripped) ====

-- SDK: Text
-- Summary: String helpers for a 40-column screen: alignment, padding, wrapping, numbers.
-- Namespaces: Text
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- Everything here returns strings or arrays of strings; the Screen and
-- Overlay frameworks draw them. Widths are in cells (bytes).

Text = Text or {}

--- Text.Plural(n, singular [, plural])
-- "1 file" / "3 files": the count and the right word.
function Text.Plural(n, singular, plural)
    if n == 1 then return n .. " " .. singular end
    return n .. " " .. (plural or (singular .. "s"))
end

-- ==== sdk: input (read-only; unused functions stripped) ====

-- SDK: Input
-- Summary: Keyboard and joystick callbacks by key or action, plus key-code names.
-- Namespaces: Input, Input.Keyboard, Input.Joystick
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- Callbacks install themselves into the program's on_keypress /
-- on_control hooks the first time one is registered, chaining to any
-- hook the program defined itself. Register them in setup().

Input = Input or {}
Input.Keyboard = Input.Keyboard or {}
Input.Joystick = Input.Joystick or {}

-- Key codes (see lua.md): ASCII for printable keys, these for the rest.
Input.KEY_RETURN = 13
Input.KEY_ESCAPE = 27
Input.KEY_BACKSPACE = 8
Input.KEY_DELETE = 127
Input.KEY_TAB = 9
Input.KEY_SPACE = 32
Input.KEY_UP = 128
Input.KEY_DOWN = 129
Input.KEY_LEFT = 130
Input.KEY_RIGHT = 131
Input.KEY_F1 = 132
Input.KEY_F2 = 133
Input.KEY_F3 = 134
Input.KEY_F4 = 135
Input.KEY_F5 = 136
Input.KEY_F6 = 137
Input.KEY_F7 = 138
Input.KEY_HOME = 139
Input.KEY_RUNSTOP = 140

local key_handlers = {}     -- key code -> fn
local key_any_handler = nil
local keyboard_installed = false

local joy_handlers = {}     -- "port:action" -> fn
local joy_state = { 0, 0 }  -- last seen direction bits per port (1-based)
local joystick_installed = false
local JOY_ACTIONS = { "up", "down", "left", "right", "fire" }

-- ==== component: header (snippet) ====

-- apps.lua — the APPS launcher (core/apps.prg).
--
-- The shell's APPS command runs this program. It lists the installed
-- applications (/apps/*.app) and games (/games/*.game) by name, version
-- and description (from each bundle's app.json) on a full screen of its
-- own. RETURN ends it with the choice, UtilityResult(true, { run = path,
-- kind = kind }), and the shell runs that program exactly as if it had
-- been typed, so a game still replaces the shell. ESC, Q or RUN/STOP
-- ends it without a choice.
--
-- It lives outside the shell so the resident shell stays small: the
-- list, its metadata and this code are only in memory while the
-- launcher is open.
--
-- Keys: UP/DOWN move, HOME first, RETURN run, ESC close. Moving the
-- selection redraws the two entries involved; only a scroll redraws the
-- list.
--
-- Built from the SPIEdit project in this folder: `swift run
-- --package-path ide/macos spibuild software/apps` (installs to core/).

-- ==== component: main (lua) ====

local COLS = Screen.COLS
local LIST_TOP = 3
local PAGE = 12                           -- entries shown: two rows each
local INNER_X, INNER_W = 1, COLS - 2
local FRAME = Attributes.Cyan
local SELECT = Attributes.Yellow + Attributes.Inverse
local GAME_TAG = Attributes.Green
local CH_POINTER, CH_UP, CH_DOWN = 16, 30, 31

local apps = {}
local selected = 1
local scroll = 0

-- One string field of a bundle's app.json (flat, generated JSON).
local function json_field(text, key)
    local s = text:find('"' .. key .. '"%s*:%s*"')
    if not s then return nil end
    local pos = text:find('"', text:find(":", s, true), true) + 1
    local parts = {}
    while pos <= #text do
        local c = text:sub(pos, pos)
        if c == '"' then return table.concat(parts) end
        if c == "\\" then
            local e = text:sub(pos + 1, pos + 1)
            parts[#parts + 1] = (e == "n" or e == "t") and " " or (e == "u" and "?" or e)
            pos = pos + (e == "u" and 6 or 2)
        else
            parts[#parts + 1] = c
            pos = pos + 1
        end
    end
    return nil
end

local function bundle_program(folder)
    local compiled = fs.find("app.prg", folder)
    if compiled then return folder .. "/" .. compiled end
    local source = fs.find("app.lua", folder)
    if source then return folder .. "/" .. source end
    return nil
end

local function scan(root, ext, kind)
    for _, entry in ipairs(fs.ls(root) or {}) do
        if entry.dir then
            local folder = root .. "/" .. entry.name
            local program = bundle_program(folder)
            if program then
                local meta = fs.readall(folder .. "/app.json") or ""
                apps[#apps + 1] = {
                    name = (json_field(meta, "name") or entry.name:gsub(ext .. "$", "")):upper(),
                    version = json_field(meta, "version") or "",
                    description = json_field(meta, "description") or "",
                    path = program,
                    kind = kind,
                }
            end
        end
    end
end

local function draw_entry(index)
    local slot = index - scroll
    if slot < 1 or slot > PAGE then return end
    local y = LIST_TOP + (slot - 1) * 2
    local app = apps[index]
    if not app then
        Screen.Clean(INNER_X, y, INNER_X + INNER_W - 1, y + 1)
        return
    end
    local chosen = index == selected
    local tag = app.kind == "game" and "GAME" or (app.version ~= "" and "V" .. app.version or "")
    local name = (chosen and string.char(CH_POINTER) or " ") .. " " .. app.name
    name = name:sub(1, INNER_W - #tag - 1)
    local attr = chosen and SELECT or 0
    Screen.Label(INNER_X, y, INNER_W, name .. string.rep(" ", INNER_W - #name - #tag) .. tag,
                 "left", attr)
    if not chosen and app.kind == "game" then
        Screen.OutText(INNER_X + INNER_W - #tag, y, tag, GAME_TAG)
    end
    Screen.Label(INNER_X, y + 1, INNER_W, "  " .. app.description, "left", attr)
end

local function draw_list()
    for i = scroll + 1, scroll + PAGE do draw_entry(i) end
    Screen.Out(COLS - 1, LIST_TOP, scroll > 0 and CH_UP or 186, FRAME)
    Screen.Out(COLS - 1, LIST_TOP + PAGE * 2 - 1,
               scroll + PAGE < #apps and CH_DOWN or 186, FRAME)
end

local function draw()
    Screen.Clear()
    Screen.Window(0, 0, COLS - 1, Screen.ROWS - 1, "APPS", Screen.DOUBLE, FRAME)
    Screen.Label(INNER_X, 1, INNER_W,
                 Text.Plural(#apps, "PROGRAM", "PROGRAMS") .. " INSTALLED", "center", 0)
    if #apps == 0 then
        Screen.CenterText(12, "NO APPS INSTALLED")
    else
        draw_list()
    end
    Screen.Label(INNER_X, Screen.ROWS - 2, INNER_W,
                 string.char(24, 25) .. " SELECT  RETURN RUN  ESC CLOSE", "center", FRAME)
end

local function move_to(index)
    index = math.max(1, math.min(index, #apps))
    if index == selected then return end
    local previous = selected
    selected = index
    local old_scroll = scroll
    if selected <= scroll then
        scroll = selected - 1
    elseif selected > scroll + PAGE then
        scroll = selected - PAGE
    end
    if scroll ~= old_scroll then
        draw_list()
    else
        draw_entry(previous)
        draw_entry(selected)
    end
end

function on_keypress(key)
    if key == Input.KEY_ESCAPE or key == Input.KEY_RUNSTOP or key == 113 or key == 81 then
        ExitProgram()
    elseif key == Input.KEY_RETURN then
        local app = apps[selected]
        if app then
            UtilityResult(true, { run = app.path, kind = app.kind })
        else
            ExitProgram()
        end
    elseif key == Input.KEY_UP then
        move_to(selected - 1)
    elseif key == Input.KEY_DOWN then
        move_to(selected + 1)
    elseif key == Input.KEY_HOME then
        move_to(1)
    end
end

function setup()
    Screen.Mode(1)
    scan("/apps", "%.app", "application")
    scan("/games", "%.game", "game")
    table.sort(apps, function(a, b) return a.name < b.name end)
    draw()
end

function tick()
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
