-- ================================================================
-- boot
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-15T20:27:00Z from components:
--   snippet header
--   lua     main
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = true


-- ==== sdk: screen (read-only; unused functions stripped) ====

-- SDK: Screen
-- Summary: Text-mode drawing on the base layer: text, boxes, fills, block moves.
-- Namespaces: Screen, Attributes
--
-- A framework file the IDE injects, read-only, into programs that
-- select it. Its format is a contract with the builder:
--   * everything above the first top-level `function` is the preamble
--     and is always emitted;
--   * each `function Name.Sub(...)` ... `end` block (both at column 0)
--     is emitted only when the program refers to Name.Sub, directly or
--     from another emitted block;
--   * a top-level `local function helper(...)` ... `end` block is
--     emitted when an emitted block refers to `helper`;
--   * the `--- Name.Sub(x, y [, attr])` line above a block is its
--     signature for completion and parameter help; the `--` lines that
--     follow describe it.
--
-- Conventions: coordinates are 0-based cells; region calls take the two
-- inclusive corners (x1, y1, x2, y2), unlike the raw ScreenX calls,
-- which take (x, y, w, h). Every call returns what the OS call returns
-- (true, or nil and a message).

Screen = Screen or {}
Screen.COLS = 40       -- cells across in the current mode (Screen.Mode updates)
Screen.ROWS = 30       -- cells down in the current mode
Screen.TEXT40 = 0      -- mode: 40x30 tiles, B&W
Screen.TEXT40C = 1     -- mode: 40x30 tiles, colour
Screen.TEXT80 = 2      -- mode: 80x60 tiles, B&W
Screen.TEXT80C = 3     -- mode: 80x60 tiles, colour
Screen.PIXELS = 10     -- mode: 320x240 pixels
Screen.PIXELS_LO = 11  -- mode: 160x120 pixels
Screen.SINGLE = 1      -- box style: single line
Screen.DOUBLE = 2      -- box style: double line
Screen.INVERT = 0x80   -- attribute bit: swap foreground and background

-- Attribute values by name, for the `attr` argument of every drawing
-- call (Screen and Overlay): a colour, plus Attributes.Inverse to paint
-- the cell's background in that colour instead of its text. Add them:
-- `Attributes.Red + Attributes.Inverse` is a red block behind a space.
-- The colours are the mode-1 default palette (entries 1-8); a program
-- that changes the palette with Screen.Palette recolours them.
Attributes = Attributes or {}
Attributes.Normal = 0          -- white text on the background, not inverted
Attributes.White = 0
Attributes.Red = 1
Attributes.Cyan = 2
Attributes.Purple = 3
Attributes.Green = 4
Attributes.Blue = 5
Attributes.Yellow = 6
Attributes.Orange = 7
Attributes.Inverse = 0x80      -- swap text and background (a coloured block for a space)

-- Console-style output: OutLine writes at the cursor row and moves on,
-- scrolling the screen when it reaches the bottom.
local cursor_row = 0

-- Inclusive corners to (x, y, w, h), in either corner order.
local function region(x1, y1, x2, y2)
    if x2 < x1 then x1, x2 = x2, x1 end
    if y2 < y1 then y1, y2 = y2, y1 end
    return x1, y1, x2 - x1 + 1, y2 - y1 + 1
end

--- Screen.Mode(mode)
-- Selects a screen mode: 0 (40x30 B&W), 1 (40x30 colour), 2 (80x60
-- B&W), 3 (80x60 colour), 10 (320x240 pixels), 11 (160x120 pixels); the
-- Screen.TEXT40 .. Screen.PIXELS_LO constants name them. Switching
-- clears the screen and sets Screen.COLS/ROWS (and Overlay's, and
-- Graphics' WIDTH/HEIGHT) to the new geometry. The pixel modes have no
-- text cells: the Graphics framework draws there.
function Screen.Mode(mode)
    local ok, err = ScreenMode(mode)
    if ok then
        local wide = mode == 2 or mode == 3
        Screen.COLS = wide and 80 or 40
        Screen.ROWS = wide and 60 or 30
        if Overlay then
            Overlay.COLS, Overlay.ROWS = Screen.COLS, Screen.ROWS
        end
        if Graphics then
            Graphics.WIDTH = mode == 11 and 160 or 320
            Graphics.HEIGHT = mode == 11 and 120 or 240
        end
    end
    return ok, err
end

--- Screen.Clear([char])
-- Fills the whole base layer with `char` (default space) and attribute 0.
function Screen.Clear(char)
    return ScreenClear(char or 32)
end

--- Screen.CenterText(y, text [, attr])
-- Writes a string centred on row `y`.
function Screen.CenterText(y, text, attr)
    text = tostring(text)
    local x = (Screen.COLS - #text) // 2
    if x < 0 then x = 0 end
    return ScreenWrite(x, y, text, attr)
end

--- Screen.Clean(x1, y1, x2, y2 [, char [, attr]])
-- Blanks the cells between two corners (inclusive): `char` defaults to
-- space and `attr` to 0.
function Screen.Clean(x1, y1, x2, y2, char, attr)
    local x, y, w, h = region(x1, y1, x2, y2)
    return ScreenFill(x, y, w, h, char or 32, attr or 0)
end

--- Screen.Palette(index, r, g, b)
-- Sets one palette entry (0 = background, 1 = default text colour).
function Screen.Palette(index, r, g, b)
    return ScreenPalette(index, r, g, b)
end

-- ==== sdk: timer (read-only; unused functions stripped) ====

-- SDK: Timer
-- Summary: Timer objects you can cancel, pause, resume and restart; one-shots and repeats.
-- Namespaces: Timer
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines). Methods on timer
-- objects (`t:Pause()`) dispatch to `Timer.Pause(t)`, and the builder
-- keeps a block when the program calls it either way.
--
-- Built on the OS timers (TimerCreate/TimerStop, 8 per program, 1 ms
-- resolution). Pause and resume are done here: a paused timer's OS
-- timer is stopped and the time left until its next fire is kept, so
-- resuming continues where it stopped rather than restarting.
-- Callbacks receive the timer object, so a handler can cancel or
-- pause its own timer. Callbacks run from the scheduler between ticks,
-- never in the middle of one.

Timer = Timer or {}

local timers = {}   -- id -> timer object, while it can still fire
local next_id = 0

-- t.id          number, unique within the program
-- t.interval    ms between fires
-- t.oneshot     true for After
-- t.fn          the callback
-- t.os_id       OS timer id while armed (nil when paused, done or cancelled)
-- t.armed_at    TimeNow() when the current OS timer was armed
-- t.remaining   ms left until the next fire while paused
-- t.catching_up true while a resumed repeating timer waits out its
--               remaining time on a one-shot before re-arming
-- t.done        true once a one-shot has fired or any timer is cancelled

local timer_mt = {
    __index = function(_, key)
        return Timer[key]
    end,
    __tostring = function(t)
        return "Timer(" .. t.id .. ")"
    end,
}

-- What happens when the OS timer behind `t` fires.
local function fire(t)
    if t.done then return end
    if t.oneshot then
        t.done = true
        t.os_id = nil
        timers[t.id] = nil
        t.fn(t)
        return
    end
    if t.catching_up then
        -- The remaining-time one-shot has fired: back to the interval.
        t.catching_up = false
        t.os_id = TimerCreate(function() fire(t) end, t.interval, false)
    end
    t.armed_at = TimeNow()
    t.fn(t)
end

-- Arm the OS timer for `t`: `first` ms until the first fire (the
-- interval, or what was left when it was paused).
local function arm(t, first)
    if t.oneshot or first ~= t.interval then
        t.catching_up = not t.oneshot
        t.os_id = TimerCreate(function() fire(t) end, first, true)
    else
        t.catching_up = false
        t.os_id = TimerCreate(function() fire(t) end, t.interval, false)
    end
    t.armed_at = TimeNow()
    t.remaining = nil
end

--- Timer.Create(fn, ms [, oneshot])
-- A timer calling fn(timer) every `ms` milliseconds, or once when
-- `oneshot` is true. Returns the timer object (its `id` field is the
-- number Timer.Get and the other calls accept). Raises an error when the
-- program's 8 OS timers are all in use.
function Timer.Create(fn, ms, oneshot)
    if type(fn) ~= "function" then error("Timer.Create: fn must be a function", 2) end
    ms = math.max(1, math.floor(tonumber(ms) or 1))
    next_id = next_id + 1
    local t = setmetatable({
        id = next_id, interval = ms, oneshot = oneshot and true or false, fn = fn,
    }, timer_mt)
    timers[t.id] = t
    arm(t, ms)
    return t
end

--- Timer.After(ms, fn)
-- Calls fn(timer) once, `ms` milliseconds from now. Returns the timer.
function Timer.After(ms, fn)
    return Timer.Create(fn, ms, true)
end

-- ==== component: header (snippet) ====

-- boot.lua — the first program the OS runs.
--
-- Shows a static startup screen for two seconds, then hands the machine
-- over to the shell with Launch(..., replace): boot leaves the program
-- stack and its Lua state is released, so only the shell stays resident.
-- If neither compiled nor source OS image can be loaded, the failure is
-- displayed on screen and this program remains running.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/boot` from the workspace root. The generated files are written
-- to software/core/

-- ==== component: main (lua) ====

-- A centred line: one display op through the Screen framework.
local function text(row, message, attr)
    Screen.CenterText(row, message, attr or 0)
end

local function draw_boot()
    Screen.Clear()
    text(8, "SPI COMPUTER", 0)
    text(10, "STARTING SYSTEM", 0)
    text(12, "PLEASE WAIT", 0)
    Screen.Clean(8, 14, 31, 14)
end

local function draw_failure()
    Screen.Clear()
    text(7, "SPI COMPUTER", 0)
    text(10, "SYSTEM STARTUP FAILED", Attributes.Inverse)
    text(13, "CANNOT FIND OS IMAGE", Attributes.Inverse)
    text(16, "EXPECTED CORE/OS.PRG", 0)
    text(17, "OR CORE/OS.LUA", 0)
    text(20, "CHECK THE SD CARD", 0)
end

-- Try each OS image once after the static startup screen has been shown.
-- Launch(..., true) replaces this program on success. A failure leaves
-- this program running with the error message on screen.
local function start_os()
    local ok = Launch("core/os.prg", nil, true)
    if not ok then
        ok = Launch("core/os.lua", nil, true)
    end
    if not ok then
        draw_failure()
    end
end

function setup()
    Screen.Mode(1)
    Screen.Palette(0, 0, 0, 160)
    Screen.Palette(1, 255, 255, 255)
    Screen.Palette(2, 180, 220, 255)
    draw_boot()
    Timer.After(2000, start_os)
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
