-- ================================================================
-- os
-- Generated by the SPIComputer IDE — do not edit this file.
-- Built 2026-09-15T21:15:04Z from components:
--   snippet header
--   lua     screen
--   lua     line-editor
--   lua     commands
--   lua     main
--   lua     tick
-- ================================================================
__spi_interactive = true
__spi_requires_video = true
__spi_requires_audio = true


-- ==== sdk: screen (read-only; unused functions stripped) ====

-- SDK: Screen
-- Summary: Text-mode drawing on the base layer: text, boxes, fills, block moves.
-- Namespaces: Screen, Attributes
--
-- A framework file the IDE injects, read-only, into programs that
-- select it. Its format is a contract with the builder:
--   * everything above the first top-level `function` is the preamble
--     and is always emitted;
--   * each `function Name.Sub(...)` ... `end` block (both at column 0)
--     is emitted only when the program refers to Name.Sub, directly or
--     from another emitted block;
--   * a top-level `local function helper(...)` ... `end` block is
--     emitted when an emitted block refers to `helper`;
--   * the `--- Name.Sub(x, y [, attr])` line above a block is its
--     signature for completion and parameter help; the `--` lines that
--     follow describe it.
--
-- Conventions: coordinates are 0-based cells; region calls take the two
-- inclusive corners (x1, y1, x2, y2), unlike the raw ScreenX calls,
-- which take (x, y, w, h). Every call returns what the OS call returns
-- (true, or nil and a message).

Screen = Screen or {}
Screen.COLS = 40       -- cells across in the current mode (Screen.Mode updates)
Screen.ROWS = 30       -- cells down in the current mode
Screen.TEXT40 = 0      -- mode: 40x30 tiles, B&W
Screen.TEXT40C = 1     -- mode: 40x30 tiles, colour
Screen.TEXT80 = 2      -- mode: 80x60 tiles, B&W
Screen.TEXT80C = 3     -- mode: 80x60 tiles, colour
Screen.PIXELS = 10     -- mode: 320x240 pixels
Screen.PIXELS_LO = 11  -- mode: 160x120 pixels
Screen.SINGLE = 1      -- box style: single line
Screen.DOUBLE = 2      -- box style: double line
Screen.INVERT = 0x80   -- attribute bit: swap foreground and background

-- Attribute values by name, for the `attr` argument of every drawing
-- call (Screen and Overlay): a colour, plus Attributes.Inverse to paint
-- the cell's background in that colour instead of its text. Add them:
-- `Attributes.Red + Attributes.Inverse` is a red block behind a space.
-- The colours are the mode-1 default palette (entries 1-8); a program
-- that changes the palette with Screen.Palette recolours them.
Attributes = Attributes or {}
Attributes.Normal = 0          -- white text on the background, not inverted
Attributes.White = 0
Attributes.Red = 1
Attributes.Cyan = 2
Attributes.Purple = 3
Attributes.Green = 4
Attributes.Blue = 5
Attributes.Yellow = 6
Attributes.Orange = 7
Attributes.Inverse = 0x80      -- swap text and background (a coloured block for a space)

-- Console-style output: OutLine writes at the cursor row and moves on,
-- scrolling the screen when it reaches the bottom.
local cursor_row = 0

--- Screen.Mode(mode)
-- Selects a screen mode: 0 (40x30 B&W), 1 (40x30 colour), 2 (80x60
-- B&W), 3 (80x60 colour), 10 (320x240 pixels), 11 (160x120 pixels); the
-- Screen.TEXT40 .. Screen.PIXELS_LO constants name them. Switching
-- clears the screen and sets Screen.COLS/ROWS (and Overlay's, and
-- Graphics' WIDTH/HEIGHT) to the new geometry. The pixel modes have no
-- text cells: the Graphics framework draws there.
function Screen.Mode(mode)
    local ok, err = ScreenMode(mode)
    if ok then
        local wide = mode == 2 or mode == 3
        Screen.COLS = wide and 80 or 40
        Screen.ROWS = wide and 60 or 30
        if Overlay then
            Overlay.COLS, Overlay.ROWS = Screen.COLS, Screen.ROWS
        end
        if Graphics then
            Graphics.WIDTH = mode == 11 and 160 or 320
            Graphics.HEIGHT = mode == 11 and 120 or 240
        end
    end
    return ok, err
end

--- Screen.Clear([char])
-- Fills the whole base layer with `char` (default space) and attribute 0.
function Screen.Clear(char)
    return ScreenClear(char or 32)
end

--- Screen.Attr(x, y, attr)
-- Sets one cell's attribute, keeping its character.
function Screen.Attr(x, y, attr)
    return ScreenAttr(x, y, attr)
end

--- Screen.ScrollUp([lines [, char [, attr]]])
-- Scrolls the whole screen up by `lines` (default 1).
function Screen.ScrollUp(lines, char, attr)
    return ScreenScroll(0, 0, Screen.COLS, Screen.ROWS, 0, -(lines or 1), char or 32, attr or 0)
end

--- Screen.Palette(index, r, g, b)
-- Sets one palette entry (0 = background, 1 = default text colour).
function Screen.Palette(index, r, g, b)
    return ScreenPalette(index, r, g, b)
end

--- Screen.Label(x, y, width, text, align [, attr])
-- Writes `text` inside a `width`-cell field, padded and aligned "left",
-- "center" or "right" (default left); longer text is cut to the field.
function Screen.Label(x, y, width, text, align, attr)
    text = tostring(text)
    if #text > width then text = text:sub(1, width) end
    local space = width - #text
    local before = 0
    if align == "center" then before = space // 2
    elseif align == "right" then before = space end
    local padded = string.rep(" ", before) .. text .. string.rep(" ", space - before)
    return ScreenWrite(x, y, padded, attr)
end

-- ==== sdk: text (read-only; unused functions stripped) ====

-- SDK: Text
-- Summary: String helpers for a 40-column screen: alignment, padding, wrapping, numbers.
-- Namespaces: Text
--
-- Same format contract as screen.lua (preamble, `function Name.Sub`
-- blocks stripped when unused, `---` signature lines).
--
-- Everything here returns strings or arrays of strings; the Screen and
-- Overlay frameworks draw them. Widths are in cells (bytes).

Text = Text or {}

--- Text.Commas(n)
-- Integer `n` with thousands separators: Text.Commas(1234567) is
-- "1,234,567".
function Text.Commas(n)
    local s = tostring(math.floor(n))
    local sign = ""
    if s:sub(1, 1) == "-" then sign, s = "-", s:sub(2) end
    local out = s:reverse():gsub("(%d%d%d)", "%1,"):reverse()
    if out:sub(1, 1) == "," then out = out:sub(2) end
    return sign .. out
end

-- ==== component: header (snippet) ====

-- os.lua — the SPIOS shell (the command line).
--
-- Started by boot at power-on; it is the OS as far as the user sees it,
-- so it has no exit command (RESET restarts the machine). Type a command
-- after READY.; HELP lists the built-ins, UTILS the installed commands.
--
-- Built-ins cover the data folder (DIR, CD, COPY, TYPE, DEL, ...), the
-- screen (CLS, MODE, COLOR), scripts (EXEC, and /data/autoexec.txt at
-- start-up) and the machine (FREE, MEM, UPTIME, VER, RESET). Anything
-- else is a program on the card, found by name in this order:
--   utils/<name>.util   utilities: run once, print their result
--   apps/<name>.app     applications: run on top of the shell
--   games/<name>.game   games: replace the shell; the device restarts
--   loose .prg/.lua     in /apps or /data
--
-- Command line: cursor keys edit, UP/DOWN recall history, TAB completes
-- command and file names (twice lists the choices), ESC clears the line.
-- "Double quotes" keep spaces in one word. `> file` or `>> file` after a
-- built-in or utility writes its output to a file instead of the screen.
-- Output longer than a screen stops at -- MORE -- (SPACE a page, RETURN a
-- line, ESC the rest).
--
-- Arguments reach programs as the global `args`: words that name a data
-- entry or look like a file name become full card paths (/data/...);
-- everything else (numbers, options, quoted words) is passed as typed.
--
-- Drawing is incremental: a finished line is one display op (plus one
-- scroll op once the screen is full), an edit redraws only the input
-- row, and the cursor is one attribute op per blink. Programs keep their
-- own screen slot, so nothing is repainted when one returns.
--
-- Memory: the shell stays resident under every program, inside the
-- 96 KB per-program heap, so rarely used commands live on the card as
-- utilities instead (HELP and UTILS run utils/help.util, COMPILE runs
-- utils/compile.util) and the cursor blinks from tick() without the
-- Timer framework.
--
-- Built from the SPIEdit project in this folder: edit the components
-- here and Build, or run `swift run --package-path ide/macos spibuild
-- software/os` from the workspace root.

local COLS, ROWS = Screen.COLS, Screen.ROWS
-- Key codes (the values of Input.KEY_*; the shell keeps them as locals
-- rather than carry the Input framework's preamble in its heap).
local KEY_RETURN, KEY_ESCAPE, KEY_BACKSPACE, KEY_DELETE, KEY_TAB = 13, 27, 8, 127, 9
local KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_HOME, KEY_RUNSTOP = 128, 129, 130, 131, 139, 140
local VERSION = "1.1"
local INVERSE = Attributes.Inverse

-- ==== component: screen (lua) ====

-- Terminal: output rows, the pager and the input row.
--
-- Output is queued (`pending`) and drained a screen at a time by flush().
-- A queued item is a line or a producer ({ next = fn, close = fn }) that
-- yields lines on demand, so TYPE streams a large file through the pager
-- without holding it. With a redirection active, output goes to `sink`
-- (a file) instead of the queue.

local row = 0              -- the row the next line (or the input) uses
local input = ""           -- the command line being typed
local caret = 0            -- 0-based caret position in `input`
local view = 0             -- first input character shown (long lines scroll)
local cursor_on = true
local cursor_col = nil     -- column the cursor attribute is on, nil when hidden
local pending, pending_head = {}, 1
local page_count = 0       -- rows shown since the user last pressed a key
local more_waiting = false -- the pager waits for a key
local sink = nil           -- redirection target: function(line)

local function advance()
    if row < ROWS - 1 then
        row = row + 1
    else
        Screen.ScrollUp(1)
    end
end

-- One finished row. Label pads to the full width with attribute 0, so it
-- replaces whatever the row held, a cursor or --MORE-- included.
local function put_row(text)
    Screen.Label(0, row, COLS, text, "left", 0)
    advance()
end

-- Queue a line or a producer (or write it straight to the redirection).
local function emit(item)
    if not sink then
        pending[#pending + 1] = item
    elseif type(item) == "string" then
        sink(item)
    else
        for line in item.next do sink(line) end
        if item.close then item.close() end
    end
end

-- Write a message; "\n" separates lines.
local function out(message)
    message = tostring(message)
    if not message:find("\n", 1, true) then
        emit(message)
        return
    end
    for part in (message .. "\n"):gmatch("([^\n]*)\n") do
        emit(part)
    end
end

-- Errors always reach the screen, even while output is redirected.
local function out_error(message)
    pending[#pending + 1] = "?" .. tostring(message)
end

local function next_line()
    while pending_head <= #pending do
        local item = pending[pending_head]
        if type(item) == "string" then
            pending[pending_head] = nil
            pending_head = pending_head + 1
            return item
        end
        local line = item.next()
        if line then return line end
        if item.close then item.close() end
        pending[pending_head] = nil
        pending_head = pending_head + 1
    end
    pending, pending_head = {}, 1
    return nil
end

local function discard_output()
    for i = pending_head, #pending do
        local item = pending[i]
        if type(item) == "table" and item.close then item.close() end
    end
    pending, pending_head = {}, 1
end

-- Show queued output. Returns true when all of it is on screen, false
-- when it stopped at a full page (the pager then waits for a key).
local function flush()
    while true do
        if page_count >= ROWS - 1 and pending_head <= #pending then
            more_waiting = true
            Screen.Label(0, row, COLS, "-- MORE --  SPACE RETURN ESC", "left", INVERSE)
            return false
        end
        local line = next_line()
        if not line then return true end
        if #line <= COLS then
            put_row(line)
            page_count = page_count + 1
        else
            for i = 1, #line, COLS do
                put_row(line:sub(i, i + COLS - 1))
                page_count = page_count + 1
            end
        end
    end
end

-- The input row: one Label op, plus the cursor's attribute.
local function draw_input()
    if caret < view then
        view = caret
    elseif caret - view > COLS - 1 then
        view = caret - (COLS - 1)
    end
    Screen.Label(0, row, COLS, input:sub(view + 1, view + COLS), "left", 0)
    cursor_col = caret - view
    if cursor_on then Screen.Attr(cursor_col, row, INVERSE) end
end

-- Leave the input row as plain text and move below it.
local function commit_input()
    cursor_col = nil
    put_row(input:sub(view + 1, view + COLS))
end

local function blink()
    cursor_on = not cursor_on
    if cursor_col then
        Screen.Attr(cursor_col, row, cursor_on and INVERSE or 0)
    end
end

local function start_input()
    input, caret, view = "", 0, 0
    cursor_on = true
    draw_input()
end

-- ==== component: line-editor (lua) ====

-- Line editor: the command line is a plain string with a caret; each key
-- changes it and redraws the input row only. UP/DOWN walk the history.

local history = {}         -- recent command lines, oldest first
local history_pos = 0      -- 0 = editing a new line
local HISTORY_MAX = 30
local complete             -- TAB completion (assigned in 30-commands)

local function remember(line)
    if line == "" or history[#history] == line then return end
    history[#history + 1] = line
    if #history > HISTORY_MAX then table.remove(history, 1) end
end

local function set_input(text)
    input = text
    caret = #text
end

local function recall(step)
    local pos = history_pos + step
    if pos < 0 or pos > #history then return end
    history_pos = pos
    set_input(pos == 0 and "" or history[#history - pos + 1])
end

-- Returns true when the key changed the line (it is then redrawn).
local function edit_key(key)
    if key == KEY_BACKSPACE then
        if caret == 0 then return false end
        input = input:sub(1, caret - 1) .. input:sub(caret + 1)
        caret = caret - 1
    elseif key == KEY_DELETE then
        if caret >= #input then return false end
        input = input:sub(1, caret) .. input:sub(caret + 2)
    elseif key == KEY_LEFT then
        caret = math.max(caret - 1, 0)
    elseif key == KEY_RIGHT then
        caret = math.min(caret + 1, #input)
    elseif key == KEY_HOME then
        caret = 0
    elseif key == KEY_UP then
        recall(1)
    elseif key == KEY_DOWN then
        recall(-1)
    elseif key == KEY_ESCAPE then
        set_input("")
        history_pos = 0
    elseif key == KEY_TAB then
        complete()
    elseif key >= 32 and key < 127 then
        if #input >= 120 then return false end
        input = input:sub(1, caret) .. string.char(key) .. input:sub(caret + 1)
        caret = caret + 1
    else
        return false
    end
    return true
end

-- ==== component: commands (lua) ====

-- Commands: paths, finding programs on the card, redirection, and the
-- built-in command table (HELP and TAB completion read it too).

local cwd = "/data"        -- real card path of the current data directory
local text_mode = 1
local waiting_child = false -- a program is running on top of the shell
local script = {}           -- queued script lines (EXEC, autoexec)
local redirect_file = nil   -- open file while output is redirected

-- ---------------------------------------------------------------- paths

local function normalize(path)
    local parts = {}
    for part in path:gmatch("[^/]+") do
        if part == ".." then
            if #parts > 0 then table.remove(parts) end
        elseif part ~= "." then
            parts[#parts + 1] = part
        end
    end
    return "/" .. table.concat(parts, "/")
end

-- A path as typed (relative to the current directory, or to the data
-- folder when it starts with "/") to its real card path under /data.
local function full_path(path)
    if not path or path == "" then return cwd end
    local logical
    if path:sub(1, 1) == "/" then
        logical = normalize(path)
    else
        logical = normalize(cwd:sub(6) .. "/" .. path)
    end
    return logical == "/" and "/data" or "/data" .. logical
end

-- A real card path as the user sees it (the data folder is "/").
local function display_path(path)
    local shown = path:gsub("^/data", "")
    return shown == "" and "/" or shown
end

-- DOS-style wildcards (* and ?) to an anchored, case-insensitive pattern.
local function wildcard(pattern)
    local lua = pattern:lower():gsub("[%^%$%(%)%%%.%[%]%+%-]", "%%%0")
    lua = lua:gsub("%*", ".*"):gsub("%?", ".")
    return "^" .. lua .. "$"
end

-- The entries of a directory argument that may end in a wildcard
-- ("*.txt", "notes/a*"): returns the directory, the matching entries
-- sorted (directories first) and the pattern, or nil and an error.
local function matching_entries(arg)
    local dir_arg, pattern = arg, nil
    if arg and arg:find("[*?]") then
        dir_arg, pattern = arg:match("^(.*)/([^/]*)$")
        if not dir_arg then dir_arg, pattern = nil, arg end
    end
    local dir = full_path(dir_arg)
    local entries, err = fs.ls(dir)
    if not entries then return nil, err end
    local list = {}
    local match = pattern and wildcard(pattern)
    for _, entry in ipairs(entries) do
        if not match or entry.name:lower():match(match) then
            list[#list + 1] = entry
        end
    end
    table.sort(list, function(a, b)
        if a.dir ~= b.dir then return a.dir end
        return a.name:lower() < b.name:lower()
    end)
    return dir, list, pattern
end

-- A file's lines on demand (a producer for the pager or a script).
local function file_lines(path)
    local f, err = fs.open(path, "r")
    if not f then return nil, err end
    local buffer, done = "", false
    local producer = {}
    function producer.close()
        if f then f:close() f = nil end
    end
    function producer.next()
        while true do
            local nl = buffer:find("\n", 1, true)
            if nl then
                local line = buffer:sub(1, nl - 1)
                buffer = buffer:sub(nl + 1)
                return (line:gsub("\r$", ""):gsub("\t", "  "))
            end
            if done then
                if buffer == "" then return nil end
                local last = buffer
                buffer = ""
                return last
            end
            local chunk = f:read(512)
            if not chunk or chunk == "" then
                done = true
                producer.close()
            else
                buffer = buffer .. chunk
            end
        end
    end
    return producer
end

-- ------------------------------------------------------------- programs

local function find_app_program(folder)
    local info = fs.stat(folder)
    if not info or not info.dir then return nil end
    local compiled = fs.find("app.prg", folder)
    if compiled then return folder .. "/" .. compiled end
    local source = fs.find("app.lua", folder)
    if source then return folder .. "/" .. source end
    return nil
end

-- A bundle's program: /<root>/<name><ext>/app.prg (or app.lua).
local function find_bundle(root, name, ext)
    local found = fs.find(name .. ext, root)
    if not found then return nil end
    return find_app_program(root .. "/" .. found)
end

-- A loose program file in /apps or /data.
local function find_program_file(name)
    for _, root in ipairs({ "/apps", "/data" }) do
        local found = fs.find(name, root)
        if found then
            local info = fs.stat(root .. "/" .. found)
            if info and not info.dir then return root .. "/" .. found end
        end
    end
    return nil
end

-- What a command name runs, and how: "utility", "application", "game"
-- or "program" (a loose .prg/.lua).
local function find_program(name)
    local lower = name:lower()
    if lower:match("%.lua$") or lower:match("%.prg$") then
        local path = find_program_file(name)
        return path, path and "program" or nil
    end
    local util = find_bundle("/utils", name, ".util")
    if util then return util, "utility" end
    local app = find_bundle("/apps", name, ".app")
    if app then return app, "application" end
    local game = find_bundle("/games", name, ".game")
    if game then return game, "game" end
    for _, candidate in ipairs({ name .. ".prg", name .. ".lua" }) do
        local path = find_program_file(candidate)
        if path then return path, "program" end
    end
    return nil
end

-- A word that looks like a file name: only name characters, a letter,
-- and a slash or an extension (notes.txt, games/x; not 2.5 or 1/3).
local function path_like(word)
    return word:match("^[%w_%-%./]+$") and word:find("%a")
        and (word:find("/", 1, true) or word:match("%.%a%w*$"))
end

-- An argument as the program sees it: data entries and file-name-like
-- words become full card paths; real card paths that exist, options,
-- numbers, expressions and quoted words pass as typed.
local function program_arg(word, quoted)
    if quoted or word:sub(1, 1) == "-" then return word end
    if word:sub(1, 1) == "/" and fs.exists(word) then return word end
    local path = full_path(word)
    if fs.exists(path) or path_like(word) then return path end
    return word
end

local function end_redirect()
    sink = nil
    if redirect_file then
        redirect_file:close()
        redirect_file = nil
    end
end

-- Run a program. A game replaces the shell (Launch with replace; the
-- device restarts when it exits); anything else runs on top, and the
-- shell carries on in its first tick after the program exits. Nothing
-- may be drawn after a successful start: the program's screen slot is
-- the one showing.
local function run_program(path, args, kind, quoted)
    quoted = quoted or {}
    local expanded = {}
    for i = 1, #args do
        local word = args[i]
        -- Wildcards expand to the matching entries' paths, as in a Unix
        -- shell (quote a pattern to pass it through: find "*.txt").
        local dir, list = nil, nil
        if not quoted[i] and word:find("[*?]") then
            dir, list = matching_entries(word)
        end
        if dir and #list > 0 then
            for _, entry in ipairs(list) do
                expanded[#expanded + 1] = dir .. "/" .. entry.name
            end
        else
            expanded[#expanded + 1] = program_arg(word, quoted[i])
        end
    end
    args = expanded
    if kind ~= "utility" then end_redirect() end
    local ok, err
    if kind == "game" then
        ok, err = Launch(path, args[1], true)
    else
        ok, err = Execute(path, table.unpack(args))
    end
    if not ok then
        out_error(err)
        return
    end
    waiting_child = true
end

-- ------------------------------------------------------------- built-ins

-- Built-in commands: lower-case name or alias -> function(args, quoted).
-- Their help text lives in the HELP utility (utils/help.util), which
-- keeps it out of the shell's heap.
local commands = {}

local function command(names, fn)
    for _, name in ipairs(names) do commands[name] = fn end
end

-- Run one of the shell's own utilities (HELP, DIR, COMPILE live on the
-- card). The shell has already resolved their arguments, so they pass
-- through as if quoted.
local function run_utility(name, args)
    local path = find_bundle("/utils", name, ".util")
    if not path then
        out_error(name:upper() .. " IS NOT INSTALLED (UTILS/" .. name:upper() .. ".UTIL)")
        return
    end
    local quoted = {}
    for i = 1, #args do quoted[i] = true end
    run_program(path, args, "utility", quoted)
end

local function need(value, usage)
    if value then return true end
    out_error("USAGE: " .. usage)
    return false
end

command({ "help", "?" }, function(a)
    run_utility("help", a)
end)

command({ "utils", "commands" }, function()
    run_utility("help", { "-utils" })
end)

command({ "compile" }, function(a)
    run_utility("compile", a)
end)

-- DIR lists through utils/dir.util: the shell hands it the directory
-- resolved against the current one, so the listing (and a big
-- directory's entry table) is built in the utility's heap, not here.
command({ "dir", "ls", "catalog" }, function(a)
    run_utility("dir", { full_path(a[1]) })
end)

command({ "cd", "chdir" }, function(a)
    local target = full_path(a[1] or "/")
    local info, err = fs.stat(target)
    if not info then out_error(err) return end
    if not info.dir then out_error("NOT A DIRECTORY") return end
    cwd = target
end)

command({ "pwd" }, function()
    out(display_path(cwd))
end)

command({ "type", "cat", "more" }, function(a)
    if not need(a[1], "TYPE <FILE>") then return end
    local producer, err = file_lines(full_path(a[1]))
    if not producer then out_error(err) return end
    emit(producer)
end)

command({ "free", "df" }, function()
    local free, total = fs.free()
    if not free then out_error("CARD SPACE UNAVAILABLE") return end
    out(string.format("%s KB FREE OF %s KB", Text.Commas(free), Text.Commas(total)))
end)

command({ "mount" }, function()
    if not fs.mount() then out_error("MOUNT FAILED") end
end)

command({ "cls", "clear", "home" }, function()
    Screen.Clear()
    row = 0
end)

-- MODE 0-3: 40x30 or 80x60, B&W or colour. The shell's geometry
-- follows Screen.COLS/ROWS, which Screen.Mode sets.
command({ "mode" }, function(a)
    if not a[1] then
        out(string.format("TEXT MODE %d (%dx%d): 0/1 40X30, 2/3 80X60", text_mode, COLS, ROWS))
        return
    end
    local mode = tonumber(a[1])
    if mode ~= 0 and mode ~= 1 and mode ~= 2 and mode ~= 3 then
        out_error("USE MODE 0, 1, 2 OR 3 (EVEN B&W, ODD COLOUR)")
        return
    end
    local ok, err = Screen.Mode(mode)
    if not ok then out_error(err) return end
    text_mode = mode
    COLS, ROWS = Screen.COLS, Screen.ROWS
    row = 0
end)

-- Named colours for COLOR (or six hex digits: COLOR FFFFFF 000080).
local COLOURS = {
    black = 0x000000, white = 0xFFFFFF, red = 0x880000, cyan = 0xAAFFEE,
    purple = 0xCC44CC, green = 0x00CC55, blue = 0x0000AA, yellow = 0xFFFF00,
    orange = 0xDD8855, grey = 0x777777, amber = 0xFFB000,
}

local function colour_value(name)
    if not name then return nil end
    local value = COLOURS[name:lower()]
    if value then return value end
    if name:match("^#?%x%x%x%x%x%x$") then return tonumber((name:gsub("#", "")), 16) end
    return nil
end

local function set_palette(index, rgb)
    Screen.Palette(index, rgb >> 16, (rgb >> 8) & 0xFF, rgb & 0xFF)
end

local function default_colours()
    set_palette(0, 0x0000AA) -- background: CPC blue
    set_palette(1, 0xFFFF00) -- text: CPC yellow
end

command({ "color", "colour" }, function(a)
    if not a[1] then
        default_colours()
        return
    end
    local fg, bg = colour_value(a[1]), colour_value(a[2])
    if not fg or (a[2] and not bg) then
        out_error("COLOURS: BLACK WHITE RED CYAN PURPLE GREEN")
        out("BLUE YELLOW ORANGE GREY AMBER, OR RRGGBB")
        return
    end
    set_palette(1, fg)
    if bg then set_palette(0, bg) end
end)

command({ "echo" }, function(a)
    out(table.concat(a, " "))
end)

command({ "mem" }, function()
    local before = collectgarbage("count")
    collectgarbage("collect")
    out(string.format("SHELL HEAP %.1f KB (%.1f BEFORE GC)",
                      collectgarbage("count"), before))
end)

command({ "history", "h" }, function()
    for i, line in ipairs(history) do
        out(string.format("%3d %s", i, line))
    end
end)

command({ "exec", "source", "batch" }, function(a)
    if not need(a[1], "EXEC <SCRIPT FILE>") then return end
    local producer, err = file_lines(full_path(a[1]))
    if not producer then out_error(err) return end
    local lines = {}
    for line in producer.next do
        local text = line:match("^%s*(.-)%s*$")
        local lower = text:lower()
        if text ~= "" and text:sub(1, 1) ~= "#" and lower ~= "rem"
            and lower:sub(1, 4) ~= "rem " then
            lines[#lines + 1] = text
        end
        if #lines >= 200 then break end
    end
    producer.close()
    for i = #lines, 1, -1 do table.insert(script, 1, lines[i]) end
end)

command({ "run" }, function(a, q)
    if not need(a[1], "RUN <PROGRAM> [ARGS]") then return end
    local path, kind = find_program(a[1])
    if not path then out_error("FILE NOT FOUND: " .. a[1]) return end
    table.remove(a, 1)
    table.remove(q, 1)
    run_program(path, a, kind, q)
end)

-- APPS runs the launcher (core/apps.prg), which ends with the chosen
-- program as its result; the shell then runs it (see 40-main).
command({ "apps" }, function()
    local path = fs.find("apps.prg", "/core") or fs.find("apps.lua", "/core")
    if not path then out_error("CORE/APPS.PRG IS MISSING") return end
    run_program("/core/" .. path, {}, "application")
end)

command({ "reset", "reboot" }, function()
    ExitProgram()
end)

-- Aliases: a first word that names one is replaced by its text. The
-- file commands are utilities on the card (utils/copy.util, ...), so
-- their familiar other names are aliases; ALIAS adds more for the
-- session (autoexec.txt is the place to keep them).
local aliases = {
    cp = "copy", rm = "del", erase = "del", mv = "ren", move = "ren",
    rename = "ren", mkdir = "md", rmdir = "rd", new = "touch", info = "stat",
    ver = "sysinfo", version = "sysinfo", uptime = "sysinfo", time = "sysinfo",
}

command({ "alias" }, function(a)
    if not a[1] then
        local names = {}
        for name in pairs(aliases) do names[#names + 1] = name end
        table.sort(names)
        for _, name in ipairs(names) do
            out(string.format("%-9s %s", name:upper(), aliases[name]))
        end
        return
    end
    local name = a[1]:lower()
    table.remove(a, 1)
    aliases[name] = #a > 0 and table.concat(a, " ") or nil
end)

-- ------------------------------------------------------------- dispatch

-- Words separated by spaces; "double quotes" keep spaces in one word and
-- mark it quoted (passed to programs exactly as typed).
local function split_words(text)
    local words, quoted = {}, {}
    local pos = 1
    while true do
        local s = text:find("%S", pos)
        if not s then break end
        if text:sub(s, s) == '"' then
            local e = text:find('"', s + 1, true) or #text + 1
            words[#words + 1] = text:sub(s + 1, e - 1)
            quoted[#words] = true
            pos = e + 1
        else
            local e = text:find("%s", s) or #text + 1
            words[#words + 1] = text:sub(s, e - 1)
            quoted[#words] = false
            pos = e
        end
    end
    return words, quoted
end

-- Take a `> file` / `>> file` (or `>file`) off the words and point the
-- output at that file until the command (or its utility) finishes.
local function take_redirect(words, quoted)
    for i = 2, #words do
        local word = words[i]
        if not quoted[i] and word:sub(1, 1) == ">" then
            local append = word:sub(1, 2) == ">>"
            local name = word:sub(append and 3 or 2)
            local used = 1
            if name == "" then
                name = words[i + 1]
                used = 2
            end
            for _ = 1, used do
                table.remove(words, i)
                table.remove(quoted, i)
            end
            if not name then return nil, "MISSING FILE NAME AFTER >" end
            local f, err = fs.open(full_path(name), append and "a" or "w")
            if not f then return nil, err end
            redirect_file = f
            sink = function(line) f:write(line .. "\n") end
            return true
        end
    end
    return true
end

local function execute(command_line)
    local words, quoted = split_words(command_line)
    if not words[1] then return end
    local ok, err = take_redirect(words, quoted)
    if not ok then out_error(err) return end
    local name = table.remove(words, 1)
    table.remove(quoted, 1)
    local alias = aliases[name:lower()]
    if alias then
        local extra, extra_quoted = split_words(alias)
        name = table.remove(extra, 1)
        table.remove(extra_quoted, 1)
        for i = #extra, 1, -1 do
            table.insert(words, 1, extra[i])
            table.insert(quoted, 1, extra_quoted[i])
        end
    end
    local builtin = commands[name:lower()]
    if builtin then
        builtin(words, quoted)
        return
    end
    local path, kind = find_program(name)
    if not path then
        out_error("FILE NOT FOUND: " .. name)
        return
    end
    run_program(path, words, kind, quoted)
end

-- ----------------------------------------------------------- completion

local last_tab = nil       -- the line at the previous TAB (twice = list)

local function common_prefix(list)
    local prefix = list[1]
    for i = 2, #list do
        local other = list[i]
        local n = 0
        while n < #prefix and n < #other
            and prefix:sub(n + 1, n + 1):lower() == other:sub(n + 1, n + 1):lower() do
            n = n + 1
        end
        prefix = prefix:sub(1, n)
    end
    return prefix
end

-- TAB: complete the word before the caret from the command names and
-- installed programs (first word) or the entries of its directory.
complete = function()
    local before = input:sub(1, caret)
    local start = before:find("[^%s\"]*$")
    local word = before:sub(start)
    local first = not before:sub(1, start - 1):find("%S")
    local dir_part = word:match("^(.*/)") or ""
    local prefix = word:sub(#dir_part + 1):lower()
    local seen, candidates = {}, {}
    local function consider(name, suffix)
        if name:lower():sub(1, #prefix) == prefix and not seen[name] then
            seen[name] = true
            candidates[#candidates + 1] = name .. suffix
        end
    end
    if first and dir_part == "" then
        for name in pairs(commands) do consider(name, " ") end
        for name in pairs(aliases) do consider(name, " ") end
        for _, root in ipairs({ "/utils", "/apps", "/games" }) do
            for _, entry in ipairs(fs.ls(root) or {}) do
                consider((entry.name:lower():gsub("%.%w+$", "")), " ")
            end
        end
    else
        for _, entry in ipairs(fs.ls(full_path(dir_part)) or {}) do
            consider(entry.name, entry.dir and "/" or " ")
        end
    end
    if #candidates == 0 then return end
    table.sort(candidates)
    local replacement
    if #candidates == 1 then
        replacement = candidates[1]
    else
        replacement = common_prefix(candidates)
        if #replacement <= #prefix then
            if last_tab == input then
                -- Second TAB: list the choices above the line.
                commit_input()
                local line = ""
                for _, candidate in ipairs(candidates) do
                    local item = candidate:gsub(" $", "")
                    if #line + #item + 2 > COLS then
                        out(line)
                        line = ""
                    end
                    line = line .. item .. "  "
                end
                out(line)
                page_count = 0
                flush()
            end
            last_tab = input
            return
        end
    end
    input = input:sub(1, start - 1) .. dir_part .. replacement .. input:sub(caret + 1)
    caret = start - 1 + #dir_part + #replacement
    last_tab = input
end

-- ==== component: main (lua) ====

-- Command flow: submit a line, finish a command (READY. or the next
-- script line), and start-up.

-- Output is on screen: run the next script line, or take input again.
local script_ready = false

local function resume()
    if #script > 0 then
        script_ready = true
    else
        start_input()
    end
end

local function finish_command()
    end_redirect()
    if #script == 0 then out("READY.") end
    if flush() then resume() end
end

local function submit(line)
    commit_input()
    page_count = 0
    execute(line)
    if not waiting_child then finish_command() end
end

-- The shell prints a program's result: a message; or a table whose
-- `message` prints first, then its `lines` in order, then every other
-- field as KEY = VALUE. A failure goes to the screen even when redirected.
local function show_utility_result(ok, result)
    -- A program may end by asking the shell to run another one (the APPS
    -- launcher does): { run = path, kind = kind [, args = {...}] }.
    if ok and type(result) == "table" and type(result.run) == "string" then
        run_program(result.run, type(result.args) == "table" and result.args or {},
                    result.kind or "application", {})
        return
    end
    if type(result) ~= "table" then
        if ok then out(result) else out_error(result) end
        return
    end
    if result.message ~= nil then
        if ok then out(result.message) else out_error(result.message) end
    end
    -- The lines are queued as one producer walking the table, so a long
    -- result does not also grow the output queue line by line.
    local lines = result.lines
    if type(lines) == "table" then
        local i = 0
        emit({ next = function()
            i = i + 1
            return lines[i] ~= nil and tostring(lines[i]) or nil
        end })
    end
    local keys = {}
    for key in pairs(result) do
        if key ~= "message" and key ~= "lines" then keys[#keys + 1] = key end
    end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
    for _, key in ipairs(keys) do
        out(string.format("%s = %s", tostring(key):upper(), tostring(result[key])))
    end
end

local function banner()
    out("")
    out("     **** SPIComputer OS v" .. VERSION .. " ****")
    out("")
    local ok, free = pcall(fs.free)
    free = (ok and type(free) == "number") and free or 0
    if free >= 1024 then
        out(string.format(" %s   SD CARD %s MB FREE", _VERSION, Text.Commas(free // 1024)))
    else
        out(string.format(" %s   SD CARD %s KB FREE", _VERSION, Text.Commas(free)))
    end
    out("")
end

function setup()
    Screen.Mode(1) -- 40x30 tiles, invert + colour
    default_colours()
    banner()
    -- /data/autoexec.txt runs at start-up, like EXEC.
    if fs.exists("/data/autoexec.txt") then
        execute("exec /autoexec.txt")
    end
    finish_command()
end

-- ==== component: tick (lua) ====

-- Main loop: finish after a program returns, route keys to the pager,
-- or the command line, and feed script lines.

local next_blink = 0

local function pager_key(key)
    if key == KEY_ESCAPE or key == KEY_RUNSTOP or key == 113 or key == 81 then
        discard_output()
        if #script == 0 then out("READY.") end
    elseif key == KEY_RETURN then
        page_count = ROWS - 2 -- one more line
    else
        page_count = 0        -- another page
    end
    more_waiting = false
    if flush() then resume() end
end

local function key_pressed(key)
    if more_waiting then
        pager_key(key)
    elseif cursor_col then
        if key == KEY_RETURN then
            local line = input
            remember(line)
            history_pos = 0
            submit(line)
        elseif edit_key(key) then
            cursor_on = true
            draw_input()
        end
    elseif key == KEY_RUNSTOP and #script > 0 then
        script = {}
        out("BREAK")
    end
end

function tick()
    -- First tick after a program exits: its result, then READY.
    if waiting_child then
        waiting_child = false
        local ok, result = UtilityPoll()
        if ok ~= nil then show_utility_result(ok, result) end
        -- The result may have started another program (APPS).
        if not waiting_child then finish_command() end
        return
    end

    while true do
        local event = InputPoll()
        if not event then break end
        if event.type == "key" and event.pressed == 1 then
            key_pressed(event.key)
            -- A program started: the rest of the keys wait for the shell.
            if waiting_child then return end
        end
    end

    if script_ready and not more_waiting then
        script_ready = false
        local line = table.remove(script, 1)
        input, view = line, 0
        submit(line)
    end

    -- The cursor blinks from here rather than from a timer: one
    -- attribute op every half second, nothing in between.
    local now = TimeNow()
    if now >= next_blink then
        next_blink = now + 500
        blink()
    end
end

function finish()
end

-- ==== generated: asset helper ====

-- Runs every asset component (tiles, palettes, sounds, scores).
-- Called from setup(); safe to call more than once.
function ApplyAssets()
    if __spi_assets then
        for _, apply in ipairs(__spi_assets) do
            apply()
        end
    end
end
